import pandas as pd
import numpy as np

def add_korean_city_names(csv_file_path, output_file_path=None):
    """
    CSV 파일에 한글도시명 열을 추가하는 함수
    
    Args:
        csv_file_path: 입력 CSV 파일 경로
        output_file_path: 출력 CSV 파일 경로 (None이면 '_with_korean_cities.csv' 추가)
    """
    
    # CSV 파일 읽기
    df = pd.read_csv(csv_file_path)
    
    # 한국에서 보편적으로 사용하는 도시명 매핑 사전
    # 주요 도시들의 영문명 -> 한글명 매핑
    city_name_mapping = {
        # 스페인
        'ACoruna': '아코루냐',
        'A Coruna': '아코루냐',
        'Madrid': '마드리드',
        'Barcelona': '바르셀로나',
        'Seville': '세비야',
        'Valencia': '발렌시아',
        'Bilbao': '빌바오',
        'Palma': '팔마',
        'Las Palmas': '라스팔마스',
        'Malaga': '말라가',
        
        # 프랑스
        'Paris': '파리',
        'Lyon': '리옹',
        'Marseille': '마르세유',
        'Nice': '니스',
        'Toulouse': '툴루즈',
        'Strasbourg': '스트라스부르',
        'Bordeaux': '보르도',
        'Lille': '릴',
        'Nantes': '낭트',
        'Montpellier': '몽펠리에',
        
        # 독일
        'Berlin': '베를린',
        'Munich': '뮌헨',
        'Frankfurt': '프랑크푸르트',
        'Hamburg': '함부르크',
        'Cologne': '쾰른',
        'Stuttgart': '슈투트가르트',
        'Dusseldorf': '뒤셀도르프',
        'Dresden': '드레스덴',
        'Leipzig': '라이프치히',
        'Hannover': '하노버',
        
        # 이탈리아
        'Rome': '로마',
        'Milan': '밀라노',
        'Naples': '나폴리',
        'Turin': '토리노',
        'Palermo': '팔레르모',
        'Genoa': '제노바',
        'Bologna': '볼로냐',
        'Florence': '피렌체',
        'Venice': '베네치아',
        'Bari': '바리',
        
        # 영국
        'London': '런던',
        'Manchester': '맨체스터',
        'Birmingham': '버밍엄',
        'Glasgow': '글래스고',
        'Edinburgh': '에든버러',
        'Liverpool': '리버풀',
        'Bristol': '브리스톨',
        'Leeds': '리즈',
        'Sheffield': '셰필드',
        'Newcastle': '뉴캐슬',
        
        # 미국
        'New York': '뉴욕',
        'Los Angeles': '로스앤젤레스',
        'Chicago': '시카고',
        'Houston': '휴스턴',
        'Phoenix': '피닉스',
        'Philadelphia': '필라델피아',
        'San Antonio': '샌안토니오',
        'San Diego': '샌디에이고',
        'Dallas': '댈러스',
        'San Jose': '산호세',
        'Austin': '오스틴',
        'Jacksonville': '잭슨빌',
        'Fort Worth': '포트워스',
        'Columbus': '콜럼버스',
        'Charlotte': '샬럿',
        'San Francisco': '샌프란시스코',
        'Indianapolis': '인디애나폴리스',
        'Seattle': '시애틀',
        'Denver': '덴버',
        'Washington': '워싱턴',
        'Boston': '보스턴',
        'El Paso': '엘패소',
        'Nashville': '내슈빌',
        'Detroit': '디트로이트',
        'Oklahoma City': '오클라호마시티',
        'Portland': '포틀랜드',
        'Las Vegas': '라스베이거스',
        'Memphis': '멤피스',
        'Louisville': '루이빌',
        'Baltimore': '볼티모어',
        'Milwaukee': '밀워키',
        'Albuquerque': '앨버커키',
        'Tucson': '투손',
        'Fresno': '프레즈노',
        'Sacramento': '새크라멘토',
        'Kansas City': '캔자스시티',
        'Mesa': '메사',
        'Atlanta': '애틀랜타',
        'Colorado Springs': '콜로라도스프링스',
        'Raleigh': '롤리',
        'Omaha': '오마하',
        'Miami': '마이애미',
        'Long Beach': '롱비치',
        'Virginia Beach': '버지니아비치',
        'Oakland': '오클랜드',
        'Minneapolis': '미니애폴리스',
        'Tulsa': '털사',
        'Tampa': '탬파',
        'Arlington': '알링턴',
        'New Orleans': '뉴올리언스',
        
        # 캐나다
        'Toronto': '토론토',
        'Montreal': '몬트리올',
        'Vancouver': '밴쿠버',
        'Calgary': '캘거리',
        'Edmonton': '에드먼턴',
        'Ottawa': '오타와',
        'Winnipeg': '위니펙',
        'Quebec City': '퀘벡시티',
        'Hamilton': '해밀턴',
        'Kitchener': '키치너',
        
        # 호주
        'Sydney': '시드니',
        'Melbourne': '멜버른',
        'Brisbane': '브리즈번',
        'Perth': '퍼스',
        'Adelaide': '애들레이드',
        'Gold Coast': '골드코스트',
        'Newcastle': '뉴캐슬',
        'Canberra': '캔버라',
        'Sunshine Coast': '선샤인코스트',
        'Wollongong': '울런공',
        
        # 일본
        'Tokyo': '도쿄',
        'Osaka': '오사카',
        'Nagoya': '나고야',
        'Sapporo': '삿포로',
        'Fukuoka': '후쿠오카',
        'Kobe': '고베',
        'Kyoto': '교토',
        'Yokohama': '요코하마',
        'Hiroshima': '히로시마',
        'Sendai': '센다이',
        'Kitakyushu': '기타큐슈',
        'Chiba': '치바',
        'Sakai': '사카이',
        'Niigata': '니가타',
        'Hamamatsu': '하마마쓰',
        'Kumamoto': '구마모토',
        'Sagamihara': '사가미하라',
        'Okayama': '오카야마',
        'Oita': '오이타',
        'Kagoshima': '가고시마',
        
        # 중국
        'Beijing': '베이징',
        'Shanghai': '상하이',
        'Guangzhou': '광저우',
        'Shenzhen': '선전',
        'Tianjin': '톈진',
        'Wuhan': '우한',
        'Dongguan': '둥관',
        'Chengdu': '청두',
        'Nanjing': '난징',
        'Chongqing': '충칭',
        'Shenyang': '선양',
        'Hangzhou': '항저우',
        'Xian': '시안',
        'Harbin': '하얼빈',
        'Suzhou': '쑤저우',
        'Qingdao': '칭다오',
        'Dalian': '다롄',
        'Zhengzhou': '정저우',
        'Shantou': '산터우',
        'Jinan': '지난',
        'Changchun': '창춘',
        'Kunming': '쿤밍',
        'Changsha': '창사',
        'Taiyuan': '타이위안',
        'Xiamen': '샤먼',
        'Hefei': '허페이',
        'Urumqi': '우루무치',
        'Fuzhou': '푸저우',
        'Wuxi': '우시',
        'Zhongshan': '중산',
        'Wenzhou': '원저우',
        'Nanning': '난닝',
        'Nanchang': '난창',
        'Guiyang': '구이양',
        'Lanzhou': '란저우',
        'Zhuhai': '주하이',
        'Changzhou': '창저우',
        'Xuzhou': '쉬저우',
        
        # 기타 아시아
        'Singapore': '싱가포르',
        'Bangkok': '방콕',
        'Manila': '마닐라',
        'Jakarta': '자카르타',
        'Kuala Lumpur': '쿠알라룸푸르',
        'Ho Chi Minh City': '호치민시',
        'Hanoi': '하노이',
        'Phnom Penh': '프놈펜',
        'Vientiane': '비엔티안',
        'Yangon': '양곤',
        'Colombo': '콜롬보',
        'Dhaka': '다카',
        'Kathmandu': '카트만두',
        'New Delhi': '뉴델리',
        'Mumbai': '뭄바이',
        'Kolkata': '콜카타',
        'Chennai': '첸나이',
        'Bangalore': '방갈로르',
        'Hyderabad': '하이데라바드',
        'Ahmedabad': '아메다바드',
        'Pune': '푸네',
        'Surat': '수라트',
        'Jaipur': '자이푸르',
        'Lucknow': '러크나우',
        'Kanpur': '칸푸르',
        'Nagpur': '나그푸르',
        'Indore': '인도르',
        'Thane': '타네',
        'Bhopal': '보팔',
        'Visakhapatnam': '비샤카파트남',
        'Pimpri-Chinchwad': '핌프리친치와드',
        'Patna': '파트나',
        'Vadodara': '바도다라',
        'Ghaziabad': '가지아바드',
        'Ludhiana': '루디아나',
        'Agra': '아그라',
        'Nashik': '나시크',
        
        # 중동
        'Dubai': '두바이',
        'Abu Dhabi': '아부다비',
        'Doha': '도하',
        'Kuwait City': '쿠웨이트시티',
        'Riyadh': '리야드',
        'Jeddah': '제다',
        'Mecca': '메카',
        'Medina': '메디나',
        'Tel Aviv': '텔아비브',
        'Jerusalem': '예루살렘',
        'Amman': '암만',
        'Beirut': '베이루트',
        'Damascus': '다마스쿠스',
        'Baghdad': '바그다드',
        'Tehran': '테헤란',
        'Istanbul': '이스탄불',
        'Ankara': '앙카라',
        'Izmir': '이즈미르',
        'Bursa': '부르사',
        'Adana': '아다나',
        'Gaziantep': '가지안테프',
        'Konya': '코니아',
        'Antalya': '안탈야',
        
        # 아프리카
        'Cairo': '카이로',
        'Lagos': '라고스',
        'Kinshasa': '킨샤사',
        'Luanda': '루안다',
        'Dar es Salaam': '다르에스살람',
        'Khartoum': '하르툼',
        'Johannesburg': '요하네스버그',
        'Alexandria': '알렉산드리아',
        'Abidjan': '아비장',
        'Casablanca': '카사블랑카',
        'Cape Town': '케이프타운',
        'Durban': '더반',
        'Nairobi': '나이로비',
        'Addis Ababa': '아디스아바바',
        'Accra': '아크라',
        'Dakar': '다카르',
        'Bamako': '바마코',
        'Ouagadougou': '와가두구',
        'Conakry': '코나크리',
        'Freetown': '프리타운',
        'Monrovia': '몬로비아',
        'Abuja': '아부자',
        'Yaoundé': '야운데',
        'Brazzaville': '브라자빌',
        'Libreville': '리브르빌',
        'Malabo': '말라보',
        'Bangui': '방기',
        'Ndjamena': '은자메나',
        'Kigali': '키갈리',
        'Kampala': '캄팔라',
        'Dodoma': '도도마',
        'Lilongwe': '릴롱궤',
        'Lusaka': '루사카',
        'Harare': '하라레',
        'Gaborone': '가보로네',
        'Maseru': '마세루',
        'Mbabane': '음바바네',
        'Maputo': '마푸토',
        'Antananarivo': '안타나나리보',
        'Port Louis': '포트루이스',
        'Victoria': '빅토리아',
        'Moroni': '모로니',
        'Tunis': '튀니스',
        'Algiers': '알제',
        'Rabat': '라바트',
        'Tripoli': '트리폴리',
        
        # 남미
        'São Paulo': '상파울루',
        'Rio de Janeiro': '리우데자네이루',
        'Salvador': '살바도르',
        'Brasília': '브라질리아',
        'Fortaleza': '포르탈레자',
        'Belo Horizonte': '벨루오리존치',
        'Manaus': '마나우스',
        'Curitiba': '쿠리치바',
        'Recife': '헤시피',
        'Porto Alegre': '포르투알레그리',
        'Belém': '벨렘',
        'Goiânia': '고이아니아',
        'Guarulhos': '과룰류스',
        'Campinas': '캄피나스',
        'São Luís': '상루이스',
        'São Gonçalo': '상곤살루',
        'Maceió': '마세이오',
        'Duque de Caxias': '두케지카시아스',
        'Nova Iguaçu': '노바이구아수',
        'Teresina': '테레지나',
        'Buenos Aires': '부에노스아이레스',
        'Córdoba': '코르도바',
        'Rosario': '로사리오',
        'Mendoza': '멘도사',
        'La Plata': '라플라타',
        'San Miguel de Tucumán': '산미겔데투쿠만',
        'Mar del Plata': '마르델플라타',
        'Salta': '살타',
        'Santa Fe': '산타페',
        'Santiago': '산티아고',
        'Valparaíso': '발파라이소',
        'Concepción': '콘셉시온',
        'La Serena': '라세레나',
        'Antofagasta': '안토파가스타',
        'Temuco': '테무코',
        'Rancagua': '란카과',
        'Talca': '탈카',
        'Arica': '아리카',
        'Chillán': '칠란',
        'Lima': '리마',
        'Arequipa': '아레키파',
        'Trujillo': '트루히요',
        'Chiclayo': '치클라요',
        'Piura': '피우라',
        'Iquitos': '이키토스',
        'Huancayo': '우안카요',
        'Chimbote': '침보테',
        'Pucallpa': '푸칼파',
        'Tacna': '타크나',
        'Bogotá': '보고타',
        'Medellín': '메데인',
        'Cali': '칼리',
        'Barranquilla': '바랑키야',
        'Cartagena': '카르타헤나',
        'Cúcuta': '쿠쿠타',
        'Soledad': '솔레다드',
        'Ibagué': '이바게',
        'Bucaramanga': '부카라망가',
        'Soacha': '소아차',
        'Caracas': '카라카스',
        'Maracaibo': '마라카이보',
        'Valencia': '발렌시아',
        'Barquisimeto': '바르키시메토',
        'Maracay': '마라카이',
        'Ciudad Guayana': '시우다드과야나',
        'San Cristóbal': '산크리스토발',
        'Maturín': '마투린',
        'Ciudad Bolívar': '시우다드볼리바르',
        'Cumana': '쿠마나',
        'Quito': '키토',
        'Guayaquil': '과야킬',
        'Cuenca': '쿠엥카',
        'Santo Domingo': '산토도밍고',
        'Machala': '마찰라',
        'Durán': '두란',
        'Manta': '만타',
        'Portoviejo': '포르토비에호',
        'Ambato': '암바토',
        'Riobamba': '리오밤바',
        'La Paz': '라파스',
        'Santa Cruz': '산타크루스',
        'Cochabamba': '코차밤바',
        'Oruro': '오루로',
        'Sucre': '수크레',
        'Potosí': '포토시',
        'Tarija': '타리하',
        'El Alto': '엘알토',
        'Asunción': '아순시온',
        'Ciudad del Este': '시우다드델에스테',
        'San Lorenzo': '산로렌소',
        'Luque': '루케',
        'Capiatá': '카피아타',
        'Lambaré': '람바레',
        'Fernando de la Mora': '페르난도델라모라',
        'Montevideo': '몬테비데오',
        'Salto': '살토',
        'Paysandú': '파이산두',
        'Las Piedras': '라스피에드라스',
        'Rivera': '리베라',
        'Maldonado': '말도나도',
        'Tacuarembó': '타쿠아렘보',
        'Melo': '멜로',
        'Mercedes': '메르세데스',
        'Artigas': '아르티가스',
        
        # 기타 유럽
        'Amsterdam': '암스테르담',
        'Rotterdam': '로테르담',
        'The Hague': '헤이그',
        'Utrecht': '위트레흐트',
        'Eindhoven': '에인트호벤',
        'Tilburg': '틸뷔르흐',
        'Groningen': '흐로닝겐',
        'Almere': '알메러',
        'Breda': '브레다',
        'Nijmegen': '네이메헌',
        'Brussels': '브뤼셀',
        'Antwerp': '안트베르펜',
        'Ghent': '겐트',
        'Charleroi': '샤를루아',
        'Liège': '리에주',
        'Bruges': '브뤼헤',
        'Namur': '나뮈르',
        'Leuven': '뢰번',
        'Mons': '몽스',
        'Aalst': '알스트',
        'Vienna': '빈',
        'Graz': '그라츠',
        'Linz': '린츠',
        'Salzburg': '잘츠부르크',
        'Innsbruck': '인스브루크',
        'Klagenfurt': '클라겐푸르트',
        'Villach': '필라흐',
        'Wels': '벨스',
        'Sankt Pölten': '잔크트푈텐',
        'Dornbirn': '도른비른',
        'Zurich': '취리히',
        'Geneva': '제네바',
        'Basel': '바젤',
        'Bern': '베른',
        'Lausanne': '로잔',
        'Winterthur': '빈터투르',
        'Lucerne': '루체른',
        'St. Gallen': '장크트갈렌',
        'Lugano': '루가노',
        'Biel/Bienne': '빌/비엔',
        'Stockholm': '스톡홀름',
        'Gothenburg': '예테보리',
        'Malmö': '말뫼',
        'Uppsala': '웁살라',
        'Västerås': '베스테로스',
        'Örebro': '외레브로',
        'Linköping': '린셰핑',
        'Helsingborg': '헬싱보리',
        'Jönköping': '욘셰핑',
        'Norrköping': '노르셰핑',
        'Oslo': '오슬로',
        'Bergen': '베르겐',
        'Trondheim': '트론헤임',
        'Stavanger': '스타방에르',
        'Bærum': '베룸',
        'Kristiansand': '크리스티안산',
        'Fredrikstad': '프레드릭스타',
        'Tromsø': '트롬쇠',
        'Sandnes': '산네스',
        'Asker': '아스케르',
        'Copenhagen': '코펜하겐',
        'Aarhus': '오르후스',
        'Odense': '오덴세',
        'Aalborg': '올보르',
        'Esbjerg': '엘스뵤르',
        'Randers': '란네르스',
        'Kolding': '콜딩',
        'Horsens': '호르센스',
        'Vejle': '바일레',
        'Roskilde': '로스킬레',
        'Helsinki': '헬싱키',
        'Espoo': '에스포',
        'Tampere': '탐페레',
        'Vantaa': '반타',
        'Oulu': '오울루',
        'Turku': '투르쿠',
        'Jyväskylä': '위베스퀼레',
        'Lahti': '라흐티',
        'Kuopio': '쿠오피오',
        'Pori': '포리',
        'Reykjavik': '레이캬비크',
        'Kópavogur': '코파보구르',
        'Hafnarfjörður': '하프나르피요르뒤르',
        'Akureyri': '아쿠레이리',
        'Garðabær': '가르다바이르',
        'Mosfellsbær': '모스펠스바이르',
        'Árborg': '아르보르크',
        'Akranes': '아크라네스',
        'Fjarðabyggð': '피야르다뷔그드',
        'Grindavík': '그린다비크',
        'Prague': '프라하',
        'Brno': '브르노',
        'Ostrava': '오스트라바',
        'Plzen': '플젠',
        'Liberec': '리베레츠',
        'Olomouc': '올로모우츠',
        'Budweis': '부드바이스',
        'Hradec Králové': '흐라데츠크랄로베',
        'Ústí nad Labem': '우스티나드라벰',
        'Pardubice': '파르두비체',
        'Warsaw': '바르샤바',
        'Krakow': '크라쿠프',
        'Lodz': '우치',
        'Wroclaw': '브로츠와프',
        'Poznan': '포즈난',
        'Gdansk': '그단스크',
        'Szczecin': '슈체친',
        'Bydgoszcz': '비드고시치',
        'Lublin': '루블린',
        'Katowice': '카토비체',
        'Budapest': '부다페스트',
        'Debrecen': '데브레첸',
        'Szeged': '세게드',
        'Miskolc': '미시콜츠',
        'Pécs': '페치',
        'Győr': '죄르',
        'Nyíregyháza': '니레지하자',
        'Kecskemét': '케치케메트',
        'Székesfehérvár': '세케시페헤르바르',
        'Szombathely': '솜바트헤이',
        'Bucharest': '부쿠레슈티',
        'Cluj-Napoca': '클루지나포카',
        'Timișoara': '티미쇼아라',
        'Iași': '야시',
        'Constanța': '콘스탄차',
        'Craiova': '크라이오바',
        'Brașov': '브라쇼브',
        'Galați': '갈라치',
        'Ploiești': '플로이에슈티',
        'Oradea': '오라데아',
        'Sofia': '소피아',
        'Plovdiv': '플로브디프',
        'Varna': '바르나',
        'Burgas': '부르가스',
        'Ruse': '루세',
        'Stara Zagora': '스타라자고라',
        'Pleven': '플레벤',
        'Sliven': '슬리벤',
        'Dobrich': '도브리치',
        'Shumen': '슈멘',
        'Belgrade': '베오그라드',
        'Novi Sad': '노비사드',
        'Niš': '니시',
        'Kragujevac': '크라구예바츠',
        'Subotica': '수보티차',
        'Novi Pazar': '노비파자르',
        'Zrenjanin': '즈렌야닌',
        'Pančevo': '판체보',
        'Čačak': '차차크',
        'Kraljevo': '크랄예보',
        'Zagreb': '자그레브',
        'Split': '스플리트',
        'Rijeka': '리예카',
        'Osijek': '오시예크',
        'Zadar': '자다르',
        'Slavonski Brod': '슬라본스키브로드',
        'Pula': '풀라',
        'Sesvete': '세스베테',
        'Karlovac': '카를로바츠',
        'Varaždin': '바라진',
        'Ljubljana': '류블랴나',
        'Maribor': '마리보르',
        'Celje': '첼례',
        'Kranj': '크란',
        'Velenje': '벨레네',
        'Koper': '코페르',
        'Novo Mesto': '노보메스토',
        'Ptuj': '프투이',
        'Trbovlje': '트르보블례',
        'Kamnik': '캄니크',
        'Sarajevo': '사라예보',
        'Banja Luka': '반야루카',
        'Tuzla': '투즐라',
        'Zenica': '제니차',
        'Mostar': '모스타르',
        'Bijeljina': '비옐리나',
        'Prijedor': '프리예도르',
        'Brčko': '브르치코',
        'Doboj': '도보이',
        'Cazin': '차진',
        'Podgorica': '포드고리차',
        'Nikšić': '닉시치',
        'Pljevlja': '플예블랴',
        'Bijelo Polje': '비옐로폴례',
        'Cetinje': '체티네',
        'Bar': '바르',
        'Herceg Novi': '헤르체그노비',
        'Berane': '베라네',
        'Budva': '부드바',
        'Golubovci': '골루보브치',
        'Skopje': '스코페',
        'Kumanovo': '쿠마노보',
        'Prilep': '프릴레프',
        'Tetovo': '테토보',
        'Veles': '벨레스',
        'Štip': '슈티프',
        'Ohrid': '오흐리드',
        'Gostivar': '고스티바르',
        'Strumica': '스트루미차',
        'Kavadarci': '카바다르치',
        'Tirana': '티라나',
        'Durrës': '두러스',
        'Vlorë': '블로러',
        'Elbasan': '엘바산',
        'Shkodër': '슈코더르',
        'Fier': '피에르',
        'Korçë': '코르처',
        'Berat': '베라트',
        'Lushnjë': '루슈네',
        'Kavajë': '카바예',
        'Athens': '아테네',
        'Thessaloniki': '테살로니키',
        'Patras': '파트라스',
        'Piraeus': '피레우스',
        'Larissa': '라리사',
        'Heraklion': '이라클리오',
        'Peristeri': '페리스테리',
        'Kallithea': '칼리테아',
        'Acharnes': '아하르네스',
        'Kalamaria': '칼라마리아',
        'Lisbon': '리스본',
        'Porto': '포르투',
        'Amadora': '아마도라',
        'Braga': '브라가',
        'Setúbal': '세투발',
        'Coimbra': '코임브라',
        'Queluz': '켈루스',
        'Funchal': '푼샬',
        'Cacém': '카셈',
        'Vila Nova de Gaia': '빌라노바지가이아',
        'Moscow': '모스크바',
        'Saint Petersburg': '상트페테르부르크',
        'Novosibirsk': '노보시비르스크',
        'Yekaterinburg': '예카테린부르크',
        'Nizhny Novgorod': '니즈니노브고로드',
        'Kazan': '카잔',
        'Chelyabinsk': '첼랴빈스크',
        'Omsk': '옴스크',
        'Samara': '사마라',
        'Rostov-on-Don': '로스토프나도누',
        'Ufa': '우파',
        'Krasnoyarsk': '크라스노야르스크',
        'Perm': '페름',
        'Voronezh': '보로네시',
        'Volgograd': '볼고그라드',
        'Krasnodar': '크라스노다르',
        'Saratov': '사라토프',
        'Tyumen': '튜멘',
        'Tolyatti': '톨리야티',
        'Izhevsk': '이제프스크',
        'Kiev': '키예프',
        'Kharkiv': '하르키우',
        'Dnipro': '드니프로',
        'Donetsk': '도네츠크',
        'Odesa': '오데사',
        'Zaporizhzhia': '자포리자',
        'Lviv': '리비우',
        'Kryvyi Rih': '크리비리흐',
        'Mykolaiv': '미콜라이우',
        'Mariupol': '마리우폴',

        # 오세아니아 추가
        'Auckland': '오클랜드',
        'Wellington': '웰링턴',
        'Christchurch': '크라이스트처치',
        'Hamilton': '해밀턴',
        'Tauranga': '타우랑가',
        'Dunedin': '더니든',
        'Palmerston North': '팔머스턴노스',
        'Napier': '네이피어',
        'Porirua': '포리루아',
        'New Plymouth': '뉴플리머스',
        'Suva': '수바',
        'Lautoka': '라우토카',
        'Nadi': '나디',
        'Labasa': '라바사',
        'Ba': '바',
        'Tavua': '타부아',
        'Levuka': '레부카',
        'Sigatoka': '시가토카',
        'Port Moresby': '포트모르즈비',
        'Lae': '라에',
        'Mount Hagen': '마운트하겐',
        'Madang': '마당',
        'Wewak': '웨와크',
        'Vanimo': '바니모',
        'Popondetta': '포폰데타',
        'Daru': '다루',
        'Kerema': '케레마',
        'Mendi': '멘디',
        'La Romana': '라로마나',
        'La Ronge': '라롱지',
        'La Seu d\'Urgell': '라세우두르젤',
        'La Tabatiere': '라타바티에르',
        'Noumea': '누메아',
        'La Tortuga': '라토르투가',
        'Villavicencio': '비야비센시오',
        'Labasa': '라바사',
        'Ozamiz': '오자미즈',
        'Labrea': '라브레아',
        'Labuan': '라부안',
        'Lac Brochet': '라크브로셰',
        'Lae Atoll': '라에환초',
        'Laeso': '라에쇠',
        'Lafayette': '라파예트',
        'LagoAgrio': '라고아그리오',
        'Cagayan de Oro': '카가얀데오로',
        'Lahad Datu': '라하드다투',
        'Terceira Island': '테르세이라섬',
        'Lake Baringo': '바링고호',
        'Gapuwiyak': '가푸위야크',
        'Lake Manyara': '만야라호',
        'Lake Minchumina': '민추미나호',
        'Lake Murray': '머레이호',
        'Barrie-Orillia': '배리오릴리아',
        'Lake Tahoe': '타호호',
        'Lakeba Island': '라케바섬',
        'Lakefield': '레이크필드',
        'Orleans': '올리언스',
        'Minocqua': '미노쿠아',
        'Lakeland': '레이크랜드',
        'Lakselv': '라크셀브',
        'Lalibela': '랄리벨라',
        'Lamen Bay': '라멘베이',
        'Lamerd': '라메르드',
        'Lamezia Terme': '라메지아테르메',
        'Lamidanda': '라미단다',
        'Lampang': '람팡',
        'Lampedusa': '람페두사',
        'Lanai City': '라나이시티',
        'Lancang': '란창',
        'Lancaster': '랭커스터',
        'Land\'sEnd': '랜즈엔드',
        'Langkawi': '랑카위',
        'Langley': '랭글리',
        'Langzhong': '랑중',
        'Lankaran': '란카란',
        'Lannion': '라니옹',
        'Lansdowne': '랜스다운',
        'Lanyu': '란위',
        'Lanzarote': '란사로테',
        'Laoag': '라오아그',
        'Lappeenranta': '라펜란타',
        'L\'Aquila': '라퀼라',
        'Laramie': '라라미',
        'Laredo': '라레도',
        'Lar': '라르',
        'Larnaca': '라르나카',
        'Larsen Bay': '라르센베이',
        'Cayo Santa Maria': '카요산타마리아',
        'Corozal': '코로살',
        'San Fernando': '산페르난도',
        'Rio Cuarto': '리오쿠아르토',
        'Lashio': '라시오',
        'Latur': '라투르',
        'Laucala Island': '라우칼라섬',
        'Bullhead City': '불헤드시티',
        'Launceston': '론세스턴',
        'Bedford': '베드포드',
        'Passo Fundo': '파소푼도',
        'Lavan Island': '라반섬',
        'Laverton': '래버턴',
        'Lawas': '라와스',
        'Lawton': '로턴',
        'Lazaro Cardenas': '라사로카르데나스',
        'Lbeck': '뤼벡',
        'Lderitz': '뤼데리츠',
        'Le Havre': '르아브르',
        'Le Mans': '르망',
        'Le Puy-en-Velay': '르퓌앙벨레',
        'Le Touquet': '르투케',
        'Hobbs': '홉스',
        'Learmonth': '리어몬스',
        'Lebak': '레박',
        'Lebanon': '레바논',
        'Tambolaka': '탐볼라카',
        'Leeds-Bradford': '리즈브래드포드',
        'Leesburg': '리스버그',
        'Allentown': '앨런타운',
        'Leinster': '레인스터',
        'Altenburg': '알텐부르크',
        'Ribeirao Preto': '히베이랑프레투',
        'Leknes': '레크네스',
        'Lelystad': '렐리스타드',
        'Salmon': '새먼',
        'Lemnos': '렘노스',
        'Lengbati': '렝바티',
        'Aizawl': '아이자울',
        'Lensk': '렌스크',
        'Leon': '레온',
        'Leonora': '레오노라',
        'Ostrava': '오스트라바',
        'Leros': '레로스',
        'Les Sables-dOlonne': '레사블돌론',
        'Leshukonskoye': '레슈콘스코예',
        'StMartin': '세인트마르틴',
        'Lethbridge': '레스브리지',
        'Lethem': '레템',
        'JemajaIsland': '제마자섬',
        'Levelock': '레벨록',
        'Levuka': '레부카',
        'Lewiston': '루이스턴',
        'Lewistown': '루이스타운',
        'Lhasa': '라사',
        'Lianyungang': '롄윈강',
        'Liberal': '리버럴',
        'Posadas': '포사다스',
        'Libo': '리보',
        'Libreville': '리브르빌',
        'Aguascalientes': '아과스칼리엔테스',
        'Toluca': '톨루카',
        'Puerto Vallarta': '푸에르토바야르타',
        'Colima City': '콜리마시티',
        'Lichinga': '리칭가',
        'Liege': '리에주',
        'Da Lat': '달랏',
        'Liepja': '리에파야',
        'Ha\'Apai': '하아파이',
        'Lihir Island': '리히르섬',
        'Lihue': '리후에',
        'Lijiang': '리장',
        'Likiep Atoll': '리키에프환초',
        'Likoma Island': '리코마섬',
        'Lilabari': '릴라바리',
        'Limbang': '림방',
        'Limoges': '리모주',
        'Limon': '리몬',
        'Lincang': '린창',
        'Lincoln': '링컨',
        'Lindi': '린디',
        'Linfen': '린펀',
        'Lingayen': '링가옌',
        'Linhares': '린야레스',
        'Linkping': '린셰핑',
        'Linyi': '린이',
        'Lipa': '리파',
        'Lipetsk': '리페츠크',
        'Liping': '리핑',
        'Lisala': '리살라',
        'Lismore': '리스모어',
        'Little Grand': '리틀그랜드',
        'Liupanshui': '류판수이',
        'Liuzhou': '류저우',
        'Livermore': '리버모어',
        'Lizard Island': '리자드섬',
        'Lleida': '예이다',
        'Lliang': '리앙',
        'Lloydminster': '로이드민스터',
        'Laghouat': '라구아트',
        'Baguio': '바기오',
        'Lockhart River': '록하트리버',
        'Lodja': '로드자',
        'Lodwar': '로드와르',
        'Loei': '뢰이',
        'Logan': '로건',
        'Logrono': '로그로뇨',
        'Loikaw': '로이카우',
        'Loiyangalani': '로이양갈라니',
        'Lokichogio': '로키초기오',
        'Guwahati': '구와하티',
        'Praya': '프라야',
        'Lompoc': '롬폭',
        'Loncopue': '론코푸에',
        'Londolozi': '론돌로지',
        'London Biggin Hill': '런던비긴힐',
        'London-Southend': '런던사우스엔드',
        'Londrina': '론드리나',
        'Long Akah': '롱아카',
        'Long Apung': '롱아풍',
        'Long Banga': '롱방가',
        'Long Beach': '롱비치',
        'Islip': '아이슬립',
        'Long Lellang': '롱렐랑',
        'Long Pasia': '롱파시아',
        'Long Seridan': '롱세리단',
        'Longana': '롱가나',
        'Longnan': '롱난',
        'Longreach': '롱리치',
        'Longyan': '롱얀',
        'Lonorore': '로노로레',
        'Lord Howe Island': '로드하우섬',
        'Loreto': '로레토',
        'Lorient': '로리앙',
        'Los Alamos': '로스알라모스',
        'San Jose del Cabo': '산호세델카보',
        'Saravena': '사라베나',
        'Monteria': '몬테리아',
        'Los Roques': '로스로케스',
        'MaliLosinj': '말리로신',
        'Kiriwina Island': '키리위나섬',
        'Luang Namtha': '루앙남타',
        'Blanc-Sablon': '블랑사블롱',
        'Luanda': '루안다',
        'Luang Prabang': '루앙프라방',
        'Luau': '루아우',
        'Lubang': '루방',
        'Lubango': '루방고',
        'Lubbock': '러벅',
        'Lublin': '루블린',
        'Lubumbashi': '루붐바시',
        'Luena': '루에나',
        'Lugano': '루가노',
        'Luhansk': '루한스크',
        'Toledo': '톨레도',
        'Lulea': '룰레오',
        'Luoyang': '뤄양',
        'Luozi': '루오지',
        'Lusambo': '루삼보',
        'Lusanga': '루상가',
        'Lutselke': '루츨케',
        'Lutsk': '루츠크',
        'Luxembourg': '룩셈부르크',
        'Luxor': '룩소르',
        'Luzhou': '루저우',
        'Saturna Island': '사투르나섬',
        'Lycksele': '뤽셀레',
        'Lydd': '리드',
        'Lynchburg': '린치버그',
        'Lynn Lake': '린레이크',
        'Lyon': '리용',
        'Lyudao': '뤼다오',
        'Bratislava': '브라티슬라바',
        'Maafaru': '마파루',
        'Maasin': '마신',
        'Maastricht': '마스트리흐트',
        'Maavarulu': '마바룰루',
        'Mabuiag Island': '마부이아그섬',
        'San Felix': '산펠릭스',
        'Macao': '마카오',
        'Mackay': '맥케이',
        'Lapu-Lapu': '라푸라푸',
        'Madang': '마당',
        'Madivaru': '마디바루',
        'Madurai': '마두라이',
        'Mae Hong Son': '매홍손',
        'Mae Sot': '매솟',
        'Rondonopolis': '혼도노폴리스',
        'Maewo': '마에워',
        'Mafeteng': '마페텡',
        'Mafia Island': '마피아섬',
        'Magan': '마간',
        'Magas': '마가스',
        'Magdeburg': '마그데부르크',
        'Twin Falls': '트윈폴스',
        'Magnitogorsk': '마그니토고르스크',
        'Magong': '마공',
        'Magway': '마그웨이',
        'Mmabatho': '마바토',
        'Bandare Mahshahr': '반다레마흐샤르',
        'Maiana': '마이아나',
        'Maiduguri': '마이두구리',
        'Sabang': '사방',
        'Maintirano': '마인티라노',
        'Maio Island': '마이오섬',
        'Majkin': '마진',
        'Varginha': '바르지냐',
        'Makemo': '마케모',
        'Makin Island': '마킨섬',
        'Makkovik': '마코비크',
        'Maku': '마쿠',
        'Makurdi': '마쿠르디',
        'Malacca': '말라카',
        'Manaoba Island': '마나오바섬',
        'Malakal': '말라칼',
        'Malanje': '말랑제',
        'Malatya': '말라티야',
        'Malda': '말다',
        'Lamap': '라맵',
        'Morowali': '모로왈리',
        'Lhokseumawe': '록세우마웨',
        'Malinau': '말리나우',
        'Malindi': '말린디',
        'Malm': '말뫼',
        'Maloelap Atol': '말로엘랍환초',
        'Malolo Lailai': '말롤로라일라이',
        'Malta': '몰타',
        'Mamburao': '맘부라오',
        'Mamitupo': '마미투포',
        'Mammoth Lakes': '매머드레이크스',
        'Man': '만',
        'Khanidanda': '카니단다',
        'Mana Island': '마나섬',
        'Mananara Nord': '마나나라노르드',
        'Mananjary': '마난자리',
        'Manassas': '마나사스',
        'Manaung': '마나웅',
        'Lamu': '라무',
        'Mandalay': '만달레이',
        'Mandera': '만데라',
        'Condoto': '콘도토',
        'Mangaia Island': '망가이아섬',
        'Mangalore': '망갈로르',
        'Manhattan': '맨해튼',
        'Manhuacu': '만우아수',
        'Manicore': '마니코레',
        'Maniitsoq': '마니이초크',
        'Maningrida': '마닝그리다',
        'Manistee': '매니스티',
        'Manitowoc': '매니토워크',
        'Manja': '만자',
        'Manley Hot Springs': '맨리핫스프링스',
        'Mannheim': '만하임',
        'Agadez': '아가데즈',
        'Mopa': '모파',
        'Manokotak': '마노코탁',
        'Manono': '마노노',
        'Mansa': '만사',
        'Mansfield': '맨스필드',
        'Mansons Landing': '맨슨스랜딩',
        'Puerto Ordaz': '푸에르토오르다스',
        'La Paz': '라파스',
        'Mazamari': '마사마리',
        'Manzhouli': '만저우리',
        'Maota': '마오타',
        'Maple Bay': '메이플베이',
        'Maprik Hayfield': '마프리크헤이필드',
        'Maputo': '마푸토',
        'Mara North': '마라노스',
        'Masai Mara': '마사이마라',
        'Maradi': '마라디',
        'Marakei': '마라케이',
        'Maratua Island': '마라투아섬',
        'Marau': '마라우',
        'Mardin': '마르딘',
        'Mare': '마레',
        'Sao Luis': '상루이스',
        'Cuiaba': '쿠이아바',
        'Mareeba': '마리바',
        'Calabar': '칼라바르',
        'Margate': '마게이트',
        'Barahona': '바라호나',
        'Nazca': '나스카',
        'Maribor': '마리보르',
        'Mariehamn': '마리에함',
        'Elba': '엘바',
        'Waisai': '와이사이',
        'Marinduque Island': '마린두케섬',
        'Iwakuni': '이와쿠니',
        'Uberaba': '우베라바',
        'Sao Carlos': '상카를로스',
        'Marion': '마리온',
        'Cuenca': '쿠엥카',
        'Maracay': '마라카이',
        'Mariupol': '마리우폴',
        'Markovo': '마르코보',
        'Marmul': '마르물',
        'Maroantsetra': '마로안체트라',
        'Marrakesh': '마라케시',
        'Marsa Alam': '마르사알람',
        'Mersa Matruh': '메르사마트루',
        'Marsh Harbour': '마시하버',
        'Marshall': '마샬',
        'Majuro': '마주로',
        'Marthas Vineyard': '마사스빈야드',
        'Baltimore': '볼티모어',
        'Fort de France': '포르드프랑스',
        'Marudi': '마루디',
        'Mary': '마리',
        'Mary\'s Harbour': '메리스하버',
        'Mashhad': '마시하드',
        'Mason City': '메이슨시티',
        'Massawa': '마사와',
        'Massena': '마세나',
        'Masset': '마셋',
        'Matadi': '마타디',
        'Wangi-wangi Island': '왕이왕이섬',
        'Mataiva': '마타이바',
        'Matak': '마탁',
        'Isiro': '이시로',
        'Easter Island': '이스터섬',
        'Pereira': '페레이라',
        'Taveuni': '타베우니',
        'Mati': '마티',
        'Manzini': '만지니',
        'Matsu': '마쓰',
        'Matsumoto': '마쓰모토',
        'Matsuyama': '마쓰야마',
        'Hambantota': '함반토타',
        'Waingapu': '와잉가푸',
        'Mauke Island': '마우케섬',
        'Maun': '마운',
        'Maupiti': '마우피티',
        'Grenada': '그레나다',
        'Dickwella': '딕웰라',
        'Mawlamyine': '마울라마인',
        'Brazzaville': '브라자빌',
        'Mayaguana': '마야과나',
        'Maymana': '마이마나',
        'Mayne Island': '메인섬',
        'Mayo': '마요',
        'Cajamarca': '카하마르카',
        'Mazar-i-Sharif': '마자르이샤리프',
        'Mbala': '음발라',
        'Mbandaka': '음반다카',
        'Mbanza-Congo': '음반자콩고',
        'Mbeya': '음베야',
        'Saginaw': '사기나우',
        'MbujiMayi': '음부지마이',
        'McAllen': '맥앨런',
        'McArthur River': '맥아더리버',
        'McCook': '맥쿡',
        'McGrath': '맥그래스',
        'Wrightstown': '라이츠타운',
        'Mecheria': '메셰리아',
        'Medicine Hat': '메디신햇',
        'Medina': '메디나',
        'Meekatharra': '미카타라',
        'Meerut': '미루트',
        'Meghauli': '메가울리',
        'Mehamn': '메함',
        'Meixian': '메이시안',
        'Mejit Island': '메지트섬',
        'Mekoryuk': '메코리육',
        'Melonguane': '멜롱과네',
        'Melilla': '멜리야',
        'Melo': '멜로',
        'Memanbetsu': '메만베츠',
        'Memmingen': '메밍겐',
        'Mendi': '멘디',
        'Menongue': '메농게',
        'Menorca': '메노르카',
        'Ponce': '폰세',
        'Meridian': '메리디안',
        'Merimbula': '메림불라',
        'Cordova': '코르도바',
        'Merowe': '메로웨',
        'Mestia': '메스티아',
        'Metlakatla': '메틀라카틀라',
        'Metz/Nancy': '메츠낭시',
        'Mexico City': '멕시코시티',
        'Meyers Chuck': '마이어스척',
        'Mfuwe': '므푸웨',
        'Miami': '마이애미',
        'Miangas': '미앙가스',
        'Mianyang': '미안양',
        'Gaspe': '가스페',
        'Greenville': '그린빌',
        'Parkersburg': '파커스버그',
        'Belleville': '벨빌',
        'Macon': '메이컨',
        'Middlemount': '미들마운트',
        'Midland': '미들랜드',
        'Tver': '트베르',
        'Constanta': '콘스탄차',
        'Yonago': '요나고',
        'Milingimbi Island': '밀링김비섬',
        'Milos': '밀로스',
        'Milwaukee': '밀워키',
        'Minamidaito': '미나미다이토',
        'Minatitlan': '미나티틀란',
        'Mineralnye Vody': '미네랄니예보디',
        'Minna': '민나',
        'Minot': '마이놋',
        'Minsk': '민스크',
        'Minto': '민토',
        'Miri': '미리',
        'MiritiParana': '미리티파라나',
        'Mirny': '미르니',
        'Misawa': '미사와',
        'Misima Island': '미시마섬',
        'Misurata': '미수라타',
        'Missoula': '미줄라',
        'Mitchell': '미첼',
        'Mitiaro Island': '미티아로섬',
        'Tripoli': '트리폴리',
        'Miyakejima': '미야케지마',
        'Miyakojima': '미야코지마',
        'Miyazaki': '미야자키',
        'Mkuze': '음쿠제',
        'Mnchengladbach': '뫼헨글라드바흐',
        'Mnster': '뮌스터',
        'Moala Island': '모알라섬',
        'Moanda': '모안다',
        'Mobile': '모빌',
        'MocImboa da Praia': '모심보아다프라이아',
        'Castro': '카스트로',
        'Modesto': '모데스토',
        'Mohenjo Daro': '모헨조다로',
        'Mogilev': '모길레프',
        'Constantine': '콘스탄틴',
        'Mohe': '모허',
        'Moheli': '모헬리',
        'Mombasa': '몸바사',
        'Mo i Rana': '뫼이라나',
        'Masbate': '마스바테',
        'Mojave': '모하비',
        'Molde': '몰데',
        'Hoolehua': '훌레후아',
        'Khonuu': '코누',
        'Manus Island': '마누스섬',
        'Monastir': '모나스티르',
        'Monbetsu': '몬베츠',
        'MongHsat': '몽샷',
        'Mongu': '몽구',
        'Monkey Bay': '몽키베이',
        'Mono Island': '모노섬',
        'Monroe': '먼로',
        'San Salvador': '산살바도르',
        'Mont-Joli': '몽졸리',
        'Mont-Tremblant': '몽트랑블랑',
        'Galiano Island': '갈리아노섬',
        'Montauk': '몬톡',
        'Fontvieille': '퐁비에유',
        'Monteagudo': '몬테아구도',
        'MonteLibano': '몬테리바노',
        'Monterey': '몬터레이',
        'Montes Claros': '몬테스클라로스',
        'Montgomery': '몽고메리',
        'Monticello': '몬티첼로',
        'Montpellier': '몽펠리에',
        'Montreal': '몬트리올',
        'Montrose': '몬트로즈',
        'Monywa': '몬이와',
        'Moomba': '뭄바',
        'Southern Pines': '서던파인스',
        'Moorea': '모레아',
        'Moosonee': '무소니',
        'Merauke': '메라우케',
        'Mopti': '모프티',
        'Mora': '모라',
        'Mundha Pande': '문다판데',
        'Morafenobe': '모라페노베',
        'Moranbah': '모란바',
        'Kraljevо': '크랄예보',
        'Moree': '모리',
        'Morgantown': '모건타운',
        'Morlaix': '모를레',
        'Mornington Island': '모닝턴섬',
        'Moro': '모로',
        'Morombe': '모롬베',
        'Morondava': '모론다바',
        'Morristown': '모리스타운',
        'Stowe': '스토우',
        'Morro de Sao Paulo': '모로데상파울로',
        'Moruya': '모루야',
        'Moser Bay': '모저베이',
        'Moshi': '모시',
        'Mosjoen': '모셴',
        'Rygge': '뤼게',
        'Mosul': '모술',
        'Mota Lava': '모타라바',
        'Errachidia': '에라치디아',
        'Moundou': '문두',
        'Mount Gambier': '마운트감비어',
        'Mount Gordon Mine': '마운트고든광산',
        'Mount Hotham': '마운트호탐',
        'Mount Isa': '마운트아이사',
        'Mount Keith': '마운트키스',
        'Mount Magnet': '마운트매그닛',
        'Mountain Home': '마운틴홈',
        'Moyo Town': '모요타운',
        'Tembagapura': '템바가푸라',
        'Mpanda': '음판다',
        'Moron': '모론',
        'Umtata': '움타타',
        'Mtwara': '음트와라',
        'Muan': '무안',
        'Bungo Regency': '붕고군',
        'Muara': '무아라',
        'Mudanjiang': '무단지앙',
        'Mudgee': '머지',        'Hohhot': '후허하오터',
        'Hokitika': '호키티카',
        'Holingol': '홀링골',
        'Hollis': '홀리스',
        'Flateyri': '플라테이리',
        'Holy Cross': '홀리크로스',
        'Homa Bay': '호마베이',
        'Homalin': '호말린',
        'Homer': '호머',
        'Hongyuan': '홍위안',
        'Honiara': '호니아라',
        'Honningsvag': '혼닝스보그',
        'Honolulu': '호놀룰루',
        'Masterton': '마스터턴',
        'Hoonah': '후나',
        'Hooper Bay': '후퍼베이',
        'Hopedale': '호프데일',
        'Horn Island': '혼섬',
        'Hornafjordur': '호르나피요르드',
        'Horta': '오르타',
        'Hoskins': '호스킨스',
        'Hot Springs': '핫스프링스',
        'Hotan': '호탄',
        'Hancock': '핸콕',
        'Hua Hin': '후아힌',
        'Huahine': '후아히네',
        'Huai\'an': '화이안',
        'Huaihua': '화이화',
        'Hualien': '화롄',
        'Huangshan': '황산',
        'Huatugou': '화투거우',
        'Hubli': '후블리',
        'Huesca': '우에스카',
        'Hughenden': '휴겐든',
        'Hughes': '휴즈',
        'Cap-Haitien': '카프아이티엥',
        'Huizhou': '후이저우',
        'Hailar': '하이라르',
        'Humberside': '험버사이드',
        'Humera': '후메라',
        'Hun': '훈',
        'Huntsville': '헌츠빌',
        'Hurghada': '후르가다',
        'Huron': '휴런',
        'Husavik': '후사비크',
        'Huslia': '후슬리아',
        'Hydaburg': '하이다버그',
        'Hyder': '하이더',
        'Ocho Rios': '오초리오스',
        'Iasi': '야시',
        'Ibadan': '이바단',
        'Ibaraki': '이바라키',
        'Ibiza': '이비자',
        'Moroni': '모로니',
        'Idaho Falls': '아이다호폴스',
        'Ifuru': '이푸루',
        'Igarka': '이가르카',
        'Igdir': '이디르',
        'Igiugig': '이기우기그',
        'Igloolik': '이글루릭',
        'Camagueuy': '카마궤이',
        'Uruapan': '우루아판',
        'Blagoveshchensk': '블라고베셴스크',
        'Igrim': '이그림',
        'Ikaria Island': '이카리아섬',
        'Iki': '이키',
        'Ilam': '일람',
        'Waala': '와알라',
        'Ile des Pins': '일데팽',
        'Iles-de-la-Madeleine': '일드라마들렌',
        'Ilheus': '일헤우스',
        'Iliamna': '일리암나',
        'Ilimanaq Harbour': '일리마나크하버',
        'Avannaata': '아반나타',
        'Ilo': '일로',
        'Iloilo': '일로일로',
        'Ilorin': '일로린',
        'Ilulissat': '일룰리사트',
        'Imperatriz': '임페라트리스',
        'Imperial': '임페리얼',
        'Imphal': '임팔',
        'In Amenas': '인아메나스',
        'In Guezzam': '인게잠',
        'In Salah': '인살라',
        'Juara': '주아라',
        'Inagua Islands': '이나과제도',
        'Juliaca': '훌리아카',
        'Independence': '인디펜던스',
        'Utopia Creek': '유토피아크리크',
        'Campeche': '캄페체',
        'Ingolstadt': '잉골슈타트',
        'Inhambane': '이냠바네',
        'Inisheer': '이니셔',
        'Inishmaan': '이니시만',
        'Inishmore': '이니시모어',
        'Inongo': '이농고',
        'Inta': '인타',
        'Inukjuak': '이누크주악',
        'Inuvik': '이누빅',
        'Invercargill': '인버카길',
        'Inverell': '인버렐',
        'Inverness': '인버네스',
        'Inyokern': '인요컨',
        'Ioannina': '요아니나',
        'Ipota': '이포타',
        'Iqaluit': '이칼루이트',
        'Iranshahr': '이란샤르',
        'Irece': '이레세',
        'Knock': '녹',
        'Iringa': '이링가',
        'Isafjrour': '이사피요르드',
        'Isfahan': '이스파한',
        'Isfana': '이스파나',
        'Ishwardi': '이시와르디',
        'Isiolo': '이시올로',
        'Pangkalanbun': '팡칼란분',
        'Islamkot': '이슬람콧',
        'Island Lake': '아일랜드레이크',
        'Islay': '아일라',
        'Ronaldsway': '로날드웨이',
        'San Domino': '산도미노',
        'Isparta': '이스파르타',
        'Tamchy': '탐치',
        'Itaituba': '이타이투바',
        'Itanhaem': '이탄하엠',
        'Ithaca': '이타카',
        'Itokama': '이토카마',
        'Ittoqqortoormiit': '이토코르토르미트',
        'Iturup': '이투루프',
        'Ivalo': '이발로',
        'Ivano-Frankivsk': '이바노프란키우스크',
        'Ivanovo': '이바노보',
        'Ivujivik': '이부지빅',
        'Iwami': '이와미',
        'Iwo Jima': '이오지마',
        'Ixiamas': '익시아마스',
        'Zihuatanejo': '시우아타네호',
        'Ixtepec': '익스테펙',
        'Izhevsk': '이제프스크',
        'Izumo': '이즈모',
        'Jabalpur': '자발푸르',
        'Barra da Tijuca': '바라다티주카',
        'Beaumont': '보몽',
        'Gulf Shores': '걸프쇼어스',
        'Port Moresby': '포트모르즈비',
        'Jacmel': '자크멜',
        'Coachella Valley': '코아첼라밸리',
        'Wilhelmshaven': '빌헬름스하펜',
        'Jaen': '하엔',
        'Jaffna': '자프나',
        'Jaffrey': '자프리',
        'Jagdalpur': '자그달푸르',
        'Grand Turk Island': '그랜드터크섬',
        'Jaguaruna': '자과루나',
        'Jahrom': '자흐롬',
        'Cienfuegos': '시엔푸에고스',
        'Jaisalmer': '자이살메르',
        'Jajao': '자자오',
        'Jalalabad': '잘랄라바드',
        'Jalal-Abad': '잘랄아바드',
        'Gorontalo': '고론탈로',
        'Jalgaon': '잘가온',
        'Jalingo': '잘링고',
        'Jaluit Island': '잘루이트섬',
        'Kangan': '칸간',
        'Jamnagar': '잠나가르',
        'Janakpur': '자낙푸르',
        'Rengat': '렝가트',
        'Jaque': '자케',
        'Cayo Coco': '카요코코',
        'Jask': '자스크',
        'Jatai': '자타이',
        'Jebel Ali': '제벨알리',
        'Jeh Island': '제섬',
        'Jeju': '제주',
        'Jeki': '제키',
        'Jengjal Baljek': '젱잘발젝',
        'Jequie': '제키에',
        'Jeremie': '제레미',
        'Jerez de la Frontera': '헤레스데라프론테라',
        'Jersey': '저지',
        'Jessore': '제소르',
        'Jeypore': '제이포르',
        'Jiagedaqi': '지아거다치',
        'Jiamusi': '지아무시',
        'Jiansanjiang': '지안산지앙',
        'Jiayuguan': '지아유관',
        'Jihlava': '지흘라바',
        'Jijel': '지젤',
        'Jinchang': '진창',
        'Jingdezhen': '징더전',
        'Ji\'an': '지안',
        'Jingzhou': '징저우',
        'Jining': '지닝',
        'Jinja': '진자',
        'Jinzhou': '진저우',
        'Ji-Parana': '지파라나',
        'Jiroft': '지로프트',
        'Jiujiang': '지우지앙',
        'Jiuzhaigou': '지우자이거우',
        'Jixi': '지시',
        'Jizan': '지잔',
        'Jnkping': '욘셰핑',
        'Maraba': '마라바',
        'Ponta Delgada': '폰타델가다',
        'Pelotas': '펠로타스',
        'Jodhpur': '조드푸르',
        'Joensuu': '요엔수',
        'Paramaribo': '파라마리보',
        'Montserrat': '몬세라트',
        'Johnstown': '존스타운',
        'Santa Ana': '산타아나',
        'Joinville': '조인빌',
        'Dehradun': '데라둔',
        'Jolo': '홀로',
        'Jomsom': '좀솜',
        'Jonesboro': '존스보로',
        'Joplin': '조플린',
        'San Jose del Guaviare': '산호세델과비아레',
        'Maicao': '마이카오',
        'Cochabamba': '코차밤바',
        'Jorhat': '조르하트',
        'Tiakur': '티아쿠르',
        'Ceiba': '세이바',
        'Bahia Solano': '바이아솔라노',
        'Coro': '코로',
        'Medellin': '메데인',
        'Havana': '하바나',
        'Maturin': '마투린',
        'Punto Fijo': '푼토피호',
        'Bulawayo': '불라와요',
        'Varadero': '바라데로',
        'Caucasia': '카우카시아',
        'Paipa': '파이파',
        'Roatan': '로아탄',
        'Oruro': '오루로',
        'El Vigia': '엘비히아',
        'Rioja': '리오하',
        'San Antonio del Tachira': '산안토니오델타치라',
        'Saba': '사바',
        'Juazeiro do Norte': '주아제이루두노르테',
        'Juba': '주바',
        'Jubail': '주바일',
        'Juina': '주이나',
        'Juist': '유이스트',
        'Julia Creek': '줄리아크리크',
        'Kaadedhdhoo Island': '카데두섬',
        'Kabale': '카발레',
        'Kaben': '카벤',
        'Kabri Dar': '카브리다르',
        'Kabul': '카불',
        'Kadanwari': '카단와리',
        'Kadapa': '카다파',
        'Kadena': '카데나',
        'Kadhdhoo Island': '카두섬',
        'Kaduqli': '카두클리',
        'Kaduna': '카두나',
        'Kaedi': '카에디',
        'Kaghau Island': '카가우섬',
        'Kagoshima': '가고시마',
        'Kahama': '카하마',
        'Kahramanmaras': '카흐라만마라시',
        'Kahului': '카훌루이',
        'Kaikoura': '카이코우라',
        'Kailashahar': '카일라샤하르',
        'HuangPing': '황핑',
        'Utarom': '우타롬',
        'Kaitaia': '카이타이아',
        'Kajaani': '카야니',
        'Kakamega': '카카메가',
        'Kake': '케이크',
        'Kalabo': '칼라보',
        'Kalaburagi': '칼라부라기',
        'Kapalua': '카팔루아',
        'Kalaleh': '칼랄레',
        'Kalamata': '칼라마타',
        'Kalamazoo': '칼라마주',
        'Kalaupapa': '칼라우파파',
        'Kalaymyo': '칼레이미오',
        'Kalbarri': '칼바리',
        'Kalemie': '칼레미',
        'Kalgoorlie': '칼구를리',
        'Kalibo': '칼리보',
        'Tanjung Redeb': '탄정레데브',
        'Kalma Wonsan': '갈마원산',
        'Kalmar': '칼마르',
        'Kalskag': '칼스카그',
        'Kaltag': '칼타그',
        'Kalumbila': '칼룸빌라',
        'Kalymnos': '칼림노스',
        'Kamalpur': '카말푸르',
        'Cyangugu': '시얀구구',
        'Kamina': '카미나',
        'Kamishly': '카미슬리',
        'Kamloops': '캠루프스',
        'Kananga': '카낭가',
        'Burqin': '부르친',
        'Kandahar': '칸다하르',
        'Kandla': '칸들라',
        'Kangding': '캉딩',
        'Kangerlussuaq': '캉엘루수아크',
        'Kangiqsualujjuaq': '캉익수알루주아크',
        'Kangiqsujuaq': '캉익수주아크',
        'Kangirsuk': '캉기르수크',
        'Kannur': '칸누르',
        'Kanpur': '칸푸르',
        'Kansas City': '캔자스시티',
        'Kaohsiung': '가오슝',
        'Paraparaumu Beach': '파라파라우무비치',
        'Kapuskasing': '카푸스카싱',
        'Karakol': '카라콜',
        'Karamay': '카라마이',
        'Karasburg': '카라스부르크',
        'Kardla': '카르들라',
        'Langgur': '랑구르',
        'Kargil': '카르길',
        'Kariba': '카리바',
        'Karlovy Vary': '카를로비바리',
        'Karlsruhe': '칼스루에',
        'Karlstad': '칼스타드',
        'Karluk': '칼룩',
        'Karonga': '카롱가',
        'Karpathos': '카르파토스',
        'Karratha': '카라타',
        'Kars': '카르스',
        'Karshi': '카르시',
        'Karumba': '카룸바',
        'Karup': '카루프',
        'Kasaan': '카산',
        'Kasabonika': '카사보니카',
        'Kasama': '카사마',
        'Kasane': '카사네',
        'Kasenga': '카센가',
        'Kasese': '카세세',
        'Kashan': '카샨',
        'Kashechewan': '카셰체완',
        'Kashgar': '카시가르',
        'Kasigluk': '카시글룩',
        'Poso': '포소',
        'Kasos Island': '카소스섬',
        'Kassala': '카살라',
        'Kassel': '카셀',
        'Kastamonu': '카스타모누',
        'Megisti': '메기스티',
        'Kastoria': '카스토리아',
        'Katima Mulilo': '카티마물릴로',
        'Katiu': '카티우',
        'Katsina': '카치나',
        'Kauehi': '카우에히',
        'Kaukura Atoll': '카우쿠라환초',
        'Kaunas': '카우나스',
        'Kavala': '카발라',
        'Kavalerovo': '카발레로보',
        'Kavieng': '카비엥',
        'Bukavu': '부카부',
        'Kawthaung': '카우타웅',
        'Kayes': '카예스',
        'Kazarman': '카자르만',
        'Durgapur': '두르가푸르',
        'Kearney': '커니',
        'Kediri Dhoho': '케디리도호',
        'Keekorok': '키코로크',
        'Keewaywin': '키와이윈',
        'Kefallinia': '케팔리니아',
        'Reykjavik': '레이캬비크',
        'Kegaska': '케가스카',
        'Kelowna': '켈로나',
        'Kemerovo': '케메로보',
        'Kemi-Tornio': '케미토르니오',
        'Kenai': '케나이',
        'Kengtung': '켕퉁',
        'Kenmore': '켄모어',
        'Kenora': '케노라',
        'Kenosha': '케노샤',
        'Keperveyem': '케페르베옘',
        'Kerben': '케르벤',
        'Kerema': '케레마',
        'Kerikeri': '케리케리',
        'Kerki': '케르키',
        'Kerman': '케르만',
        'Kerry': '케리',
        'Majalengka': '마잘렝카',
        'Kerteh': '케르테',
        'Keshod': '케쇼드',
        'Ketchikan': '케치칸',
        'Key West': '키웨스트',
        'Khabarovsk': '하바롭스크',
        'Khamti': '캄티',
        'Khanty-Mansiysk': '한티만시스크',
        'Kharg Island': '카르그섬',
        'Khartoum': '하르툼',
        'Khasab': '카사브',
        'Khatanga': '카탕가',
        'Khatgal': '카트갈',
        'Kherson': '헤르손',
        'Khmelnytsky': '흐멜니츠키',
        'Lopburi': '롭부리',
        'Khon Kaen': '콘깬',
        'Khorog': '호로그',
        'Khorramabad': '호라마바드',
        'Khost': '호스트',
        'Khotang': '호탕',
        'Khovd': '호브드',
        'Khoy': '호이',
        'Kaliningrad': '칼리닌그라드',
        'Khujand': '후잔드',
        'Narok': '나로크',
        'Kiel': '킬',
        'Kigoma': '키고마',
        'Kihihi': '키히히',
        'Kikai': '키카이',
        'Kikori': '키코리',
        'Kili Island': '킬리섬',
        'Kilimanjaro': '킬리만자로',
        'Killeen': '킬린',
        'Kilwa Masoko': '킬와마소코',
        'Kimberley': '킴벌리',
        'Kimmirut': '키미루트',
        'Kindu': '킨두',
        'King Cove': '킹코브',
        'King Island': '킹아일랜드',
        'King Salmon': '킹새먼',
        'Kingfisher Lake': '킹피셔레이크',
        'Kingman': '킹맨',
        'Kingscote': '킹스코트',
        'Kingston': '킹스턴',
        'Kinmen': '킨먼',
        'Kinston': '킨스턴',
        'Kipnuk': '킵누크',
        'Kirakira': '키라키라',
        'Grumeti': '그루메티',
        'Kirensk': '키렌스크',
        'Kirkenes': '키르케네스',
        'Kirksville': '커크스빌',
        'Kirkuk': '키르쿠크',
        'Kirkwall': '커크월',
        'Kirovsk-Apatity': '키롭스크아파티티',
        'Kiruna': '키루나',
        'Kish Island': '키시섬',
        'Kismayo': '키스마요',
        'Kisumu': '키수무',
        'Kitadaito': '키타다이토',
        'Kitale': '키탈레',
        'Kythira': '키티라',
        'Kitoi Bay': '키토이베이',
        'Kittila': '키틸라',
        'Kiunga': '키웅가',
        'Kivalina': '키발리나',
        'Klagbay': '클라그베이',
        'Klamath Falls': '클래머스폴스',
        'Klawock': '클라워크',
        'Klemtu': '클렘투',
        'Rockland': '록랜드',
        'Kobuk': '코북',
        'Kochi': '코치',
        'Kogalym': '코갈림',
        'Koggala': '코갈라',
        'Kokhanok': '코하노크',
        'Kokkola-Pietarsaari': '코콜라피에타르사리',
        'Kokoda': '코코다',
        'Kokshetau': '콕셰타우',
        'Kolda': '콜다',
        'Kolhapur': '콜하푸르',
        'Koliganek': '콜리가넥',
        'Kolwezi': '콜웨지',
        'Komatsu': '고마쓰',
        'Dessie': '데시',
        'Komo-Manda': '코모만다',
        'Labuan Bajo': '라부안바조',
        'Komsomolsk-on-Amur': '콤소몰스크나아무레',
        'Kona': '코나',
        'ChahBahar': '차바하르',
        'Kone': '코네',
        'Kongiganak': '콩기가나크',
        'Kongolo': '콩골로',
        'Kooddoo': '쿠두',
        'Korhogo': '코르호고',
        'Korla': '코를라',
        'Koro Island': '코로섬',
        'Koromiko': '코로미코',
        'Kortrijk': '코르트레이크',
        'Kos': '코스',
        'Kosice': '코시체',
        'Kosrae': '코스라에',
        'Kostanay': '코스타나이',
        'Kostroma': '코스트로마',
        'Kota': '코타',
        'Kota Kinabalu': '코타키나발루',
        'Kotlas': '코틀라스',
        'Kotlik': '코틀릭',
        'Koulamoutou': '쿨라무투',
        'Koumac': '쿠마크',
        'Kowanyama': '코완야마',
        'Koyuk': '코육',
        'Koyukuk': '코유쿠크',
        'Kozani': '코자니',
        'Kozushima': '코즈시마',
        'Krabi': '크라비',
        'Krasnoselkup': '크라스노셀쿠프',
        'Baikonur': '바이코누르',
        'Kristiansand': '크리스티안산',
        'Kristianstad': '크리스티안스타드',
        'Kristiansund': '크리스티안순드',
        'Mbombela': '음봄벨라',
        'Krui': '크루이',
        'Kao': '카오',
        'Kubin': '쿠빈',
        'Kuching': '쿠칭',
        'Kudat': '쿠다트',
        'Kufra': '쿠프라',
        'Kugaaruk': '쿠가루크',
        'Kugluktuk': '쿠글룩투크',
        'Kuito': '쿠이토',
        'Kukes': '쿠케스',
        'Kulhudhuffush': '쿨후두푸시',
        'Kulob': '쿨로브',
        'Kulusuk': '쿨루수크',
        'Kumejima': '쿠메지마',
        'Kunduz': '쿤두즈',
        'Uherske Hradiste': '우헤르스케흐라디슈테',
        'Kuqa': '쿠차',
        'Kuressaare': '쿠레사레',
        'Kurgan': '쿠르간',
        'Kuria': '쿠리아',
        'Orvakal': '오르바칼',
        'Kursk': '쿠르스크',
        'Kushiro': '구시로',
        'Kutacane': '쿠타차네',
        'Kutahya': '쿠타히야',
        'Kuujjuaq': '쿠주아크',
        'Kuujjuarapik': '쿠주아라피크',
        'Kuusamo': '쿠사모',
        'Kuwait': '쿠웨이트',
        'Kwailabesi': '콰일라베시',
        'Kwethluk': '쿠에틀룩',
        'Kwigillingok': '쿠이길링고크',
        'Kyaukpyu': '쿄크퓨',
        'Kyzyl': '키질',
        'Kyzyl-Kiya': '키질키야',
        'Kyzylorda': '키질로르다',
        'Wolf Point': '울프포인트',
        'Guatemala City': '과테말라시티',
        'La Chorrera': '라초레라',
        'La Crosse': '라크로스',
        'La Cumbre': '라쿰브레',
        'Tumaco': '투마코',
        'Fortuna': '포르투나',
        'La Fria': '라프리아',
        'La Gomera': '라고메라',
        'Radisson River': '래디슨리버',
        'La Macarena': '라마카레나',
        'Saint-Tropez': '생트로페',
        'Manizales': '마니살레스',
        'La Pedrera': '라페드레라',
        'La Plata': '라플라타',
        'La Primavera': '라프리마베라',
        'La Rochelle': '라로셸',
        'La Romaine': '라로멘',
        'La Romana': '라로마나',
        'DongHoi': '동호이',
        'Tuy Hoa': '투이호아',
        'Dongola': '동골라',
        'Dongying': '동잉',
        'Uliastai': '울리아스타이',
        'Arunachal Pradesh': '아루나찰프라데시',
        'Doomadgee': '둠마지',
        'Dortmund': '도르트문트',
        'Dothan': '도탄',
        'Douala': '두알라',
        'St Andrew Parish': '세인트앤드류교구',
        'Dourados': '두라도스',
        'Dover': '도버',
        'Valera': '발레라',
        'Pedro Juan Caballero': '페드로후안카바예로',
        'Baler': '발러',
        'Mariscal Estigarribia': '마리스칼에스티가리비아',
        'Drake Bay': '드레이크베이',
        'Fayetteville': '페이어트빌',
        'Dresden': '드레스덴',
        'Dryden': '드라이든',
        'Dubbo': '더보',
        'Dublin': '더블린',
        'DuBois': '뒤부아',
        'Dubrovnik': '두브로브니크',
        'Dubuque': '더뷰크',
        'Duluth': '덜루스',
        'Dumka': '둠카',
        'Dundee': '던디',
        'Dundo': '둔도',
        'Dunedin': '더니든',
        'Dunhuang': '둔황',
        'Dunk Island': '덩크섬',
        'West Chicago': '웨스트시카고',
        'Duqm': '두크',
        'Durango': '두랑고',
        'Dushanbe': '두샨베',
        'Dutse': '둣세',
        'Dzaoudzi': '자우지',
        'Eagle': '이글',
        'Vail/Eagle': '베일이글',
        'Eagle River': '이글리버',
        'East Hampton': '이스트햄프턴',
        'Kununurra': '쿠누누라',
        'East Midlands': '이스트미들랜즈',
        'Longview': '롱뷰',
        'Pendleton': '펜들턴',
        'Bishop': '비숍',
        'Martinsburg': '마틴스버그',
        'College Station': '컬리지스테이션',
        'Eastmain': '이스트메인',
        'EbonIsland': '에본섬',
        'Abakaliki': '아바칼리키',
        'Ed Daein': '에드다에인',
        'Eday': '에데이',
        'Edinburgh': '에든버러',
        'Macas': '마카스',
        'Edna Bay': '에드나베이',
        'San Vicente': '산비센테',
        'Little Cayman': '리틀케이맨',
        'Galena': '갤리나',
        'Pormpuraaw': '포름푸라우',
        'Edwards': '에드워즈',
        'Eek': '이크',
        'Egegik': '에게지크',
        'Egilsstaoir': '에길스스타오이르',
        'Eindhoven': '에인트호벤',
        'Eirunepe': '에이루네페',
        'Ejin Banner': '에진기',
        'Ekuk': '에쿠크',
        'Ekwok': '에쿠오크',
        'El Aguacate': '엘아과카테',
        'Yopal': '요팔',
        'El Arish': '엘아리시',
        'El Bagre': '엘바그레',
        'El Bayadh': '엘바야드',
        'El Bolson': '엘볼손',
        'Quibdo': '키브도',
        'Armenia': '아르메니아',
        'Providencia Island': '프로비덴시아섬',
        'El Fasher': '엘파셔',
        'El Golea': '엘골레아',
        'Valverde': '발베르데',
        'NewValley': '뉴밸리',
        'Jalapa': '할라파',
        'Calama': '칼라마',
        'El Nido': '엘니도',
        'El Obeid': '엘오베이드',
        'El Palomar': '엘팔로마르',
        'El Porvenir': '엘포르베니르',
        'Poza Rica': '포사리카',
        'Puerto Madryn': '푸에르토마드린',
        'Puerto Montt': '푸에르토몬트',
        'El Tigre': '엘티그레',
        'El Tor': '엘토르',
        'Santa Cruz': '산타크루스',
        'Elazig': '엘라지',
        'Elcho Island': '엘초섬',
        'Eldoret': '엘도레트',
        'Mejato Island': '메하토섬',
        'Elfin Cove': '엘핀코브',
        'Elim': '엘림',
        'Elista': '엘리스타',
        'Elko': '엘코',
        'Ellisras': '엘리스라스',
        'Rapid City': '래피드시티',
        'Elmira': '엘마이라',
        'Elrose Mine': '엘로즈광산',
        'Ely': '일리',
        'Embu': '엠부',
        'Emerald': '에메랄드',
        'Emmen': '에멘',
        'Emmonak': '에모낙',
        'Emo': '에모',
        'Enarotali': '에나로탈리',
        'Enejit': '에네지트',
        'Enewetak': '에네웨타크',
        'Enfidha': '엔피다',
        'Enggano Island': '엥가노섬',
        'Enontekio': '에논테키오',
        'Colon': '콜론',
        'David': '다비드',
        'Enschede': '엔스헤데',
        'Enshi': '언시',
        'Entebbe': '엔테베',
        'Atiu Island': '아티우섬',
        'epinal': '에피날',
        'Erbil': '에르빌',
        'Yerbogachen': '예르보가첸',
        'Ercan': '에르잔',
        'Erechim': '에레심',
        'Erenhot': '에렌호트',
        'Erfurt': '에르푸르트',
        'Erie': '이리',
        'Whitehorse': '화이트호스',
        'Kayseri': '카이세리',
        'Prescott': '프레스콧',
        'Windhoek': '빈트후크',
        'Erzincan': '에르진잔',
        'Erzurum': '에르주룸',
        'Esbjerg': '에스비에르',
        'Esperance': '에스페란스',
        'Esquel': '에스켈',
        'Essaouira': '에사우이라',
        'Essen': '에센',
        'Eua': '에우아',
        'Eugene': '유진',
        'Mayaguez': '마야과스',
        'Basel': '바젤',
        'Mulhouse': '뮐루즈',
        'Evansville': '에반스빌',
        'Antique': '안티케',
        'Ewer': '이워',
        'Excursion': '익스커전',
        'Exeter': '엑시터',
        'GeorgeTown': '조지타운',
        'Echeng District': '어청구',
        'StEustatius': '세인트유스타티우스',
        'Tahiti': '타히티',
        'Faaite': '파아이테',
        'MitU': '미투',
        'Apia': '아피아',
        'Fagernes': '파게르네스',
        'Fahud': '파후드',
        'Fair Isle': '페어아일',
        'Spokane': '스포케인',
        'Faisalabad': '파이살라바드',
        'Fakahina': '파카히나',
        'Fakarava': '파카라바',
        'Fakfak': '파크파크',
        'Falam Surbung': '팔람수르붕',
        'Falgunand': '팔구난드',
        'International Falls': '인터내셔널폴스',
        'False Pass': '폴스패스',
        'Fane': '파네',
        'Fangatau': '팡가타우',
        'Trujillo': '트루히요',
        'Pucallpa': '푸칼파',
        'Piura': '피우라',
        'Chiclayo': '치클라요',
        'Farafangana': '파라팡가나',
        'Farah': '파라',
        'Faranah': '파라나',
        'Faresmaathodaa': '파레스마토다',
        'Farnborough': '판버러',
        'Faro': '파로',
        'Farrukhabad': '파루카바드',
        'Fasa': '파사',
        'Nosy Be': '노시베',
        'Bengkulu': '벵쿨루',
        'Faya Largeau': '파야라르고',
        'Fayzabad': '파이자바드',
        'Rimini': '리미니',
        'Granada': '그라나다',
        'Feira de Santana': '페이라데산타나',
        'Fengning': '펑닝',
        'Fera Island': '페라섬',
        'Sibolga': '시볼가',
        'Fergana': '페르가나',
        'Fernando de Noronha': '페르난도드노론하',
        'Fez': '페스',
        'Fianarantsoa': '피아나란초아',
        'Figari': '피가리',
        'Lopez Island': '로페스섬',
        'Fitiuta': '피티우타',
        'Fitzroy Crossing': '피츠로이크로싱',
        'Flagstaff': '플래그스태프',
        'Kralendijk': '크랄렌다이크',
        'Flin Flon': '플린플론',
        'Flinders Island': '플린더스섬',
        'Florence': '플로렌스',
        'Flores Island': '플로레스섬',
        'Marathon': '마라톤',
        'Floro': '플뢰뢰',
        'Lahr': '라르',
        'Foggia': '포자',
        'Fond-du-Lac': '퐁뒤라크',
        'Fonte Boa': '폰테보아',
        'Iron Mountain': '아이언마운틴',
        'Forde': '포르데',
        'Forli': '포를리',
        'Formosa': '포르모사',
        'Fort Albany': '포트알바니',
        'Fort Chipewyan': '포트치페와얀',
        'Fort Collins': '포트콜린스',
        'Fort Dodge': '포트다지',
        'Fort Frances': '포트프랜시스',
        'Fort Good Hope': '포트굿호프',
        'Fort Hope': '포트호프',
        'Fort McMurray': '포트맥머리',
        'Fort McPherson': '포트맥퍼슨',
        'Fort Resolution': '포트레졸루션',
        'Fort Severn': '포트세번',
        'Fort Simpson': '포트심슨',
        'Fort Smith': '포트스미스',
        'Fort St. John': '포트세인트존',
        'Los Mochis': '로스모치스',
        'Fort Wayne': '포트웨인',
        'Fort Yukon': '포트유콘',
        'Cloudbreak': '클라우드브레이크',
        'Foshan': '포산',
        'Foula': '폴라',
        'Farmington': '파밍턴',
        'Foya': '포야',
        'Foz do Iguacu': '포스두이구아수',
        'Franca': '프랑카',
        'Franceville': '프랑스빌',
        'Juiz de Fora': '주이스데포라',
        'Busuanga': '부수앙가',
        'Francisco Beltrao': '프란시스코벨트랑',
        'Jauja': '하우하',
        'Humaita': '우마이타',
        'Coca': '코카',
        'Porto': '포르투',
        'Torreon': '토레온',
        'Francistown': '프랜시스타운',
        'Marilia': '마릴리아',
        'Holguin': '올긴',
        'Lautzenhausen': '라우첸하우젠',
        'Biak': '비아크',
        'Ruteng': '루텡',
        'Maumere': '마우메레',
        'Fredericton': '프레더릭턴',
        'Friday Harbor': '프라이데이하버',
        'Hailey-Sun Valley': '헤일리선밸리',
        'Friedrichshafen': '프리드리히스하펜',
        'Nukualofa': '누쿠알로파',
        'Fuerte Olimpo': '푸에르테올림포',
        'Fuerteventura': '푸에르테벤투라',
        'Fujairah': '푸자이라',
        'Fukue': '푸쿠에',
        'Fukushima': '후쿠시마',
        'Funadhoo': '푸나두',
        'Funafuti': '푸나푸티',
        'Futuna Island': '푸투나섬',
        'Fuvahmulah': '푸바물라',
        'Fuyang': '푸양',
        'Fuyuan': '푸위안',
        'Fuyun': '푸윈',
        'Fuzuli': '푸줄리',
        'Gabes': '가베스',
        'Tame': '타메',
        'Gachsaran': '가치사란',
        'Gafsa': '가프사',
        'Kangra': '캉그라',
        'GAllivare': '갈리바레',
        'Galway': '골웨이',
        'Galela': '갈렐라',
        'Gamba': '감바',
        'Gambela': '감벨라',
        'Gambell': '감벨',
        'Gan Island': '간섬',
        'Gander': '간더',
        'Ganges': '갠지스',
        'Ganja': '간자',
        'Xiahe': '샤허',
        'Ruijin': '루이진',
        'Gao': '가오',
        'Garachine': '가라치네',
        'Sirte': '시르테',
        'Garden City': '가든시티',
        'GardenPnt': '가든포인트',
        'Garissa': '가리사',
        'Garoua': '가루아',
        'Garowe': '가로웨',
        'Gary': '게리',
        'Garze County': '간제현',
        'Gatineau': '가티노',
        'Gatokae': '가토카에',
        'Gaua Island': '가우아섬',
        'Siddharthanagar': '싯다르타나가르',
        'Gaya': '가야',
        'Gaziantep': '가지안테프',
        'GazipaSa': '가지파샤',
        'Gdynia Kosakowo': '그디니아코사코보',
        'Geita': '게이타',
        'Gelendzhik': '겔렌지크',
        'Gelephu': '겔레푸',
        'Gemena': '게메나',
        'Geneina': '게네이나',
        'Chillan': '칠란',
        'Comodoro Rivadavia': '코모도로리바다비아',
        'Morelia': '모렐리아',
        'Tampico': '탐피코',
        'Durango': '두랑고',
        'Veracruz': '베라크루스',
        'Hermosillo': '에르모시요',
        'Guaymas': '과이마스',
        'Parana': '파라나',
        'Rio Verde': '리우베르데',
        'Zacatecas': '사카테카스',
        'Reynosa': '레이노사',
        'Cuernavaca': '쿠에르나바카',
        'Ciudad Victoria': '시우다드빅토리아',
        'General Pico': '헤네랄피코',
        'Mazatlan': '마사틀란',
        'Chihuahua': '치와와',
        'Mexicali': '멕시칼리',
        'General Santos': '헤네랄산토스',
        'Matamoros': '마타모로스',
        'Purwokerto': '푸르워케르토',
        'Salinas': '살리나스',
        'Peoria': '피오리아',
        'Geneva': '제네바',
        'George': '조지',
        'Belfast': '벨파스트',
        'StLucia': '세인트루시아',
        'Geraldton': '제럴드턴',
        'Buenaventura': '부에나벤투라',
        'Puerto Carreno': '푸에르토카레뇨',
        'Larantuka': '라란투카',
        'Ghadames': '가다메스',
        'Ghat': '가트',
        'Ghazni': '가즈니',
        'Mascara': '마스카라',
        'Gibraltar': '지브롤터',
        'Gilgit': '길기트',
        'Gillam': '길람',
        'Gillette': '질레트',
        'Ginbata': '긴바타',
        'Girona': '지로나',
        'Popondetta': '포폰데타',
        'Gisborne': '기즈번',
        'Gisenyi': '기세니',
        'Gjgur': '교구르',
        'Gjoa Haven': '요아헤이븐',
        'Kalispell': '칼리스펠',
        'Gladstone': '글래드스톤',
        'Vitoria da Conquista': '비토리아다콘키스타',
        'Gloucester': '글로스터',
        'Viedma': '비에드마',
        'Jujuy': '후후이',
        'Gode': '고데',
        'Caticlan': '카티클란',
        'Gods Lake Narrows': '갓스레이크내로우스',
        'Gods River': '갓스리버',
        'Ironwood': '아이언우드',
        'Golfito': '골피토',
        'Tolu': '톨루',
        'Golmud': '골무드',
        'Golog': '골로그',
        'La Ceiba': '라세이바',
        'Golovin': '골로빈',
        'Goma': '고마',
        'Gombe': '곰베',
        'Gomel': '고멜',
        'Gondar': '곤다르',
        'Gondia': '곤디아',
        'Goodnews Bay': '굿뉴스베이',
        'Gorakhpur': '고라크푸르',
        'Gordon': '고든',
        'Gorgan': '고르간',
        'Gorge Harbour': '고지하버',
        'Gorna Oryahovitsa': '고르나오리아호비차',
        'Gorno-Altaysk': '고르노알타이스크',
        'Goroka': '고로카',
        'Mossoro': '모소로',
        'Nhulunbuy': '눌룬부이',
        'Porto Velho': '포르투벨류',
        'Governor\'s Harbour': '거버너스하버',
        'Goya': '고야',
        'Kaluga': '칼루가',
        'Gracias': '그라시아스',
        'Graciosa': '그라시오사',
        'LasPalmas': '라스팔마스',
        'Freeport': '프리포트',
        'Whitmore': '휘트모어',
        'Grand Canyon': '그랜드캐년',
        'Peach Springs': '피치스프링스',
        'Grand Forks': '그랜드포크스',
        'Grand Junction': '그랜드정션',
        'Grande Prairie': '그란데프레리',
        'Silver': '실버',
        'Moses Lake': '모세스레이크',
        'Bridgetown': '브리지타운',
        'Grants Pass': '그랜츠패스',
        'Grayling': '그레이링',
        'Great Bend': '그레이트벤드',
        'Great Falls': '그레이트폴스',
        'Great Harbour Cay': '그레이트하버케이',
        'Binghamton': '빙엄턴',
        'Moncton': '몽크턴',
        'Rochester': '로체스터',
        'Lewisburg': '루이스버그',
        'Greensburg': '그린스버그',
        'Greenway Sound': '그린웨이사운드',
        'Greenwood': '그린우드',
        'PuertoPlata': '푸에르토플라타',
        'Nuwara Eliya': '누와라엘리야',
        'Grenoble': '그르노블',
        'Griffith': '그리피스',
        'Grimsey': '그림시',
        'Grise Fiord': '그라이스피오르드',
        'Grodno': '그로드노',
        'Groote Eylandt': '그루트아일랜트',
        'Grosseto': '그로세토',
        'Grozny': '그로즈니',
        'Gruyere': '그뤼에르',
        'Guadalajara': '과달라하라',
        'Guanaja': '과나하',
        'Guanambi': '과남비',
        'Guangyuan': '광위안',
        'Guantanamo': '관타나모',
        'Guapi': '과피',
        'Guarapari': '과라파리',
        'Guarapuava': '과라푸아바',
        'Puerto Williams': '푸에르토윌리엄스',
        'Guasdualito': '과스두알리토',
        'GuayaramerIn': '과야라메린',
        'Guelmim': '겔미',
        'El Oued': '엘우에드',
        'The Forest': '더포레스트',
        'Guerrero Negro': '게레로네그로',
        'Guilin': '계림',
        'Popayan': '포파얀',
        'Gunnison': '거니슨',
        'Gunsan': '군산',
        'Oksibil': '옥시빌',
        'Gurayat': '구라야트',
        'Guriel': '구리엘',
        'Alotau': '알로타우',
        'Gusau': '구사우',
        'StBarthelemy': '세인트바르텔레미',
        'Florencia': '플로렌시아',
        'Baracoa': '바라코아',
        'San Andres Island': '산안드레스섬',
        'Gustavus': '구스타부스',
        'Kotabaru': '코타바루',
        'Guyuan': '구위안',
        'Gwadar': '과다르',
        'Lawrenceville': '로렌스빌',
        'Gyor': '죄르',
        'Selayar Islands': '셀라야르제도',
        'Sampit': '삼피트',
        'Ende': '엔데',
        'Tanjung Pandan': '탄정판단',
        'Hachijo jima': '하치조지마',
        'Hagerstown': '헤이거스타운',
        'Hagfors': '하그포르스',
        'Haifa': '하이파',
        'Haikou': '하이커우',
        'Haines': '헤인스',
        'Hakkari': '하카리',
        'Hakodate': '하코다테',
        'Hall Beach': '홀비치',
        'Halls Creek': '홀스크리크',
        'Halmstad': '할름스타드',
        'Kendari': '켄다리',
        'Hamadan': '하마단',
        'Hami': '하미',
        'Hamilton Island': '해밀턴섬',
        'Hammerfest': '함메르페스트',
        'Hana': '하나',
        'Hanamaki': '하나마키',
        'Bar Harbor': '바하버',
        'Handan': '한단',
        'Batam': '바탐',
        'Hanimaadhoo': '하니마두',
        'Hanover': '하노버',
        'Hanzhong': '한중',
        'Hao': '하오',
        'Harrisburg': '해리스버그',
        'Livingstone': '리빙스턴',
        'Harstad-Narvik': '하르스타드나르비크',
        'Hartford': '하트포드',
        'Laayoune': '라아유네',
        'Hassi R\'Mel': '하시르멜',
        'Hasvik': '하스비크',
        'Hat Yai': '하얏',
        'Hatay': '하타이',
        'Laurel': '로렐',
        'Haugesund': '하우게순드',
        'Havasupai': '하바수파이',
        'Havre': '하브르',
        'Havre-Saint-Pierre': '하브르생피에르',
        'Vinnytsia': '빈니차',
        'Chester': '체스터',
        'Jackson': '잭슨',
        'Hawthorne': '호손',
        'Hay River': '헤이리버',
        'Hays': '헤이스',
        'Hayward': '헤이워드',
        'Turkistan': '투르키스탄',
        'Healy Lake': '힐리레이크',
        'Hechi': '허치',
        'Fargo': '파고',
        'Belmopan': '벨모판',
        'Heho': '헤호',
        'Heihe': '헤이허',
        'Hejing': '허징',
        'Helena': '헬레나',
        'Heligoland': '헬리골란트',
        'Hemavan': '헤마반',
        'Sand Island': '샌드아일랜드',
        'Phalaborwa': '팔라보르와',
        'Hengchun': '헝춘',
        'Hengyang': '헝양',
        'Saint Croix': '세인트크로이',
        'Heraklion': '이라클리오',
        'Herat': '헤라트',
        'Florianopolis': '플로리아노폴리스',
        'Heringsdorf': '헤링스도르프',
        'Pottstown': '포츠타운',
        'Las Tunas': '라스투나스',
        'Puebla': '푸에블라',
        'Rio Grande': '리우그란데',
        'Hervey Bay': '허비베이',
        'Heviz': '헤비즈',
        'Heze': '허저',
        'Kramfors-Solleftea': '크람포르스솔레프테오',
        'High Level': '하이레벨',
        'Higuerote': '히게로테',
        'Wallis Island': '월리스섬',
        'Hikueru': '히쿠에루',
        'Hilo': '힐로',
        'Hilton Head Island': '힐턴헤드아일랜드',
        'Hilversum': '힐베르쉼',
        'Hindon': '힌던',
        'Hingurakgoda': '힌구라고다',
        'Hisar': '히사르',
        'Ho': '호',
        'Hoarafushi': '호아라푸시',
        'Hobart': '호바트',
        'Hudaydah': '후다이다',
        'Hof': '호프',
        'Hohhot': '후허',
        'Lucas do Rio Verde': '루카스두리우베르지',
        'Bom Jesus': '봄제수스',
        'Boma': '보마',
        'Bonaventure': '보나벤처',
        'Bonito': '보니토',
        'Bonne Terre': '본테레',
        'Tarawa': '타라와',
        'Boolgeeda': '불기다',
        'Harrison': '해리슨',
        'Bora Bora': '보라보라',
        'Bordj Badji Mokhtar': '보르즈바지모크타르',
        'Borg El Arab': '보르그엘아랍',
        'Borkum': '보르쿰',
        'Bornholm': '보른홀름',
        'Borongan': '보롱간',
        'Lashkar Gah': '라시카르가',
        'Bouake': '부아케',
        'Bouarfa': '부아르파',
        'Bechar': '베샤르',
        'Boulder City': '볼더시티',
        'Boulia': '불리아',
        'Phongsaly': '퐁살리',
        'Bourke': '버크',
        'Bournemouth': '본머스',
        'Bowling Green': '볼링그린',
        'Bozeman': '보즈먼',
        'Bradford': '브래드포드',
        'Windsor Locks': '윈저록스',
        'Braganca': '브라간사',
        'Brahmapur': '브라마푸르',
        'Brainerd': '브레이너드',
        'Brak': '브라크',
        'Brampton Island': '브램턴섬',
        'Brandon': '브랜던',
        'Branson': '브랜슨',
        'Brasov': '브라쇼프',
        'Bratsk': '브라츠크',
        'Braunschweig': '브라운슈바이크',
        'Bremen': '브레멘',
        'Brescia': '브레시아',
        'Brest': '브레스트',
        'Brevig Mission': '브레비그미션',
        'Bridgewater': '브리지워터',
        'San Luis': '산루이스',
        'Brindisi': '브린디시',
        'Brive-la-Gaillarde': '브리브라가야르드',
        'Brno': '브르노',
        'Isle of Skye': '스카이섬',
        'Brochet': '브로셰',
        'Brockville': '브록빌',
        'Broken Hill': '브로큰힐',
        'Bronnoysund': '브뢴뇌순드',
        'Brookings': '브루킹스',
        'Broome': '브룸',
        'Madison': '매디슨',
        'Bandar Seri Begawan': '반다르스리브가완',
        'Brunswick': '브런즈윅',
        'Brus Laguna': '브루스라구나',
        'Brussels': '브뤼셀',
        'Charleroi': '샤를루아',
        'Bryansk': '브랸스크',
        'Concord': '콩코드',
        'Kwajalein': '콰잘레인',
        'Buckland': '버클랜드',
        'Buffalo': '버팔로',
        'Chiredzi': '치레지',
        'Bugulma': '부굴마',
        'Bujumbura': '부줌부라',
        'Buka Island': '부카섬',
        'Bukhara': '부하라',
        'Bukoba': '부코바',
        'Bulagtai': '불라그타이',
        'Bulgan': '불간',
        'Pekaulang': '페카울랑',
        'Bulolo': '불롤로',
        'Bumba': '붐바',
        'Bundaberg': '번다버그',
        'Bunia': '부니아',
        'Buon Ma Thuot': '부온마투옷',
        'Burgas': '부르가스',
        'Burgos': '부르고스',
        'Buriram': '부리람',
        'Burketown': '버크타운',
        'Burlington': '벌링턴',
        'Burnie': '버니',
        'Bushehr': '부셰르',
        'Busselton': '버셀턴',
        'Butaritari Atoll': '부타리타리환초',
        'Butembo': '부템보',
        'Bydgoszcz': '비드고시치',
        'Ca Mau': '까마우',
        'Cabinda': '카빈다',
        'Upland': '업랜드',
        'Cabo Frio': '카보프리우',
        'Pedernales': '페데르날레스',
        'Cacador': '카사도르',
        'Caceres': '카세레스',
        'Cachoeiro de Itapemirim': '카쇼에이루지이타페미림',
        'Puerto Ayacucho': '푸에르토아야쿠초',
        'Tarapoto': '타라포토',
        'Cotonou': '코토누',
        'Caen': '캉',
        'Lal-lo': '랄로',
        'Cagliari': '칼리아리',
        'Cairns': '케언스',
        'Cajazeiras': '카자제이라스',
        'Calais-Dunkerque': '칼레덩케르크',
        'Calayan Island': '칼라얀섬',
        'Calbayog': '칼바요그',
        'Caldas Novas': '칼다스노바스',
        'Calvi': '칼비',
        'NhaTrang': '나트랑',
        'Cambridge': '케임브리지',
        'Cambridge Bay': '케임브리지베이',
        'Camden': '캠든',
        'Mambajao': '맘바자오',
        'CUcuta': '쿠쿠타',
        'Hopkinsville': '홉킨스빌',
        'Campbell River': '캠벨리버',
        'Campbeltown': '캠벨타운',
        'Campina Grande': '캄피나그란데',
        'Campinas Amarais': '캄피나스아마라이스',
        'Campo Grande': '캄포그란데',
        'CanTho': '껀터',
        'Saguenay-Bagotville': '사게네바고트빌',
        'Cranbrook': '크랜브룩',
        'Canaima': '카나이마',
        'canakkale': '차나칼레',
        'Osorno': '오소르노',
        'Canberra': '캔버라',
        'Cancun': '칸쿤',
        'Roseau': '로조',
        'Canela': '카넬라',
        'Nuoliang Township': '뉴올리앙향',
        'Cangzhou': '창저우',
        'Cannes': '칸',
        'Canouan': '카누안',
        'Moab': '모압',
        'Cap Skirring': '캅스키링',
        'Tumbes': '툼베스',
        'Cape Barren Island': '케이프배런섬',
        'Cape Dorset': '케이프도싯',
        'Cape Girardeau': '케이프지라도',
        'Cape Lisburne': '케이프리스번',
        'Cape Winelands': '케이프와인랜즈',
        'Harrisburg': '해리스버그',
        'Cacoal': '카코알',
        'Lansing': '랜싱',
        'SanIgnacio': '산이그나시오',
        'Pisco': '피스코',
        'Talara': '탈라라',
        'San Borja': '산보르하',
        'SanJulian': '산훌리안',
        'Tarija': '타리하',
        'La Rioja': '라리오하',
        'Cobija': '코비하',
        'Potosi': '포토시',
        'La Palma': '라팔마',
        'Capurgana': '카푸르가나',
        'Car Nicobar': '카르니코바르',
        'Caracarai': '카라카라이',
        'Parauapebas': '파라우아페바스',
        'Carauari': '카라우아리',
        'Caravelas': '카라벨라스',
        'Carcassonne': '카르카손',
        'Cardiff': '카디프',
        'Athan': '아탄',
        'Carlisle': '칼라일',
        'Esmeraldas': '에스메랄다스',
        'Bayamo': '바야모',
        'Villahermosa': '비야에르모사',
        'Carnarvon': '카나본',
        'Concepcion': '콘셉시온',
        'PlayaSamara': '플라야사마라',
        'Cartago': '카르타고',
        'Cartwright': '카트라이트',
        'Caruaru': '카루아루',
        'Casablanca': '카사블랑카',
        'Cascais': '카스카이스',
        'Cascavel': '카스카벨',
        'Casper': '캐스퍼',
        'Christmas Island': '크리스마스섬',
        'Castellon de la Plana': '카스테욘델라플라나',
        'Merced': '머시드',
        'Hatton': '해튼',
        'Castres': '카스트르',
        'Haiphong': '하이퐁',
        'Cat Lake': '캣레이크',
        'Catalina': '카탈리나',
        'Catania': '카타니아',
        'Iguazu': '이구아수',
        'Catarman': '카타르만',
        'Catbalogan': '카트발로간',
        'Catumbela': '카툼벨라',
        'Cauayan': '카우아얀',
        'Puerto Leguizamo': '푸에르토레기사모',
        'Carlsbad': '칼스배드',
        'Caxambu': '카샴부',
        'Caxias do Sul': '카시아스두술',
        'CayeCaulker': '카예코커',
        'CayeChapel': '카예채플',
        'Cayenne': '카옌',
        'Cedar City': '시더시티',
        'Ceduna': '세두나',
        'Kocaeli': '코자엘리',
        'Central': '센트럴',
        'Bloomington': '블루밍턴',
        'Grand Island': '그랜드아일랜드',
        'Mosinee': '모시니',
        'Riverton': '리버턴',
        'Taytay': '타이타이',
        'Sao Vicente': '상비센테',
        'Ceske Budejovice': '체스케부데요비체',
        'Cold Lake': '콜드레이크',
        'GooseBay': '구스베이',
        'Chachapoyas': '차차포야스',
        'Chadron': '채드론',
        'Barretos': '바헤토스',
        'Chaghcharan': '차그차란',
        'Chaiten': '차이텐',
        'Chalkyitsik': '찰키치크',
        'Vatry': '바트리',
        'Chambery': '샹베리',
        'Chandigarh': '찬디가르',
        'Chandrapur': '찬드라푸르',
        'Baishan': '바이산',
        'Changde': '창더',
        'Changhai': '창하이',
        'Changuinola': '찬기놀라',
        'Changzhi': '창즈',
        'Chania': '하니아',
        'Chaoyang': '차오양',
        'Chara': '차라',
        'Cayman Brac': '케이맨브라크',
        'Santa Rosa': '산타로사',
        'Charleville': '샤를빌',
        'Charlevoix': '샤를부아',
        'Charlo': '샤를로',
        'Charlottesville': '샬러츠빌',
        'Charlottetown': '샬럿타운',
        'Chateauroux': '샤토루',
        'Chattanooga': '채터누가',
        'Chaurjhari': '차우르자리',
        'Jamestown': '제임스타운',
        'Cheboksary': '체복사리',
        'Georgetown': '조지타운',
        'Chefornak': '체포르낙',
        'Chelinda': '첼린다',
        'Chenga': '체냐가',
        'Chengde': '청더',
        'Chenzhou': '천저우',
        'Cheongju': '청주',
        'Cherbourg-Octeville': '셰르부르옥트빌',
        'Cherepovets': '체레포베츠',
        'Al Hoceima': '알호세이마',
        'Cherkasy': '체르카시',
        'Chernivtsi': '체르니우치',
        'Traverse City': '트래버스시티',
        'Chersky': '체르스키',
        'Chesterfield': '체스터필드',
        'Chetumal': '체투말',
        'Chevak': '체박',
        'Chevery': '셰브리',
        'Cheyenne': '샤이엔',
        'Chiang Mai': '치앙마이',
        'Chiang Rai': '치앙라이',
        'Chiayi': '자이',
        'Chibougamau': '시부가모',
        'Chichen Itza': '치첸이트사',
        'Chichijima': '치치지마',
        'Chicken': '치킨',
        'Chico': '치코',
        'Port Elizabeth': '포트엘리자베스',
        'Chifeng': '츠펑',
        'Chignik': '치그닉',
        'Chignik Lagoon': '치그닉라군',
        'Chignik Lake': '치그닉레이크',
        'Blantyre': '블랜타이어',
        'Chillagoe': '칠라고',
        'Kundiawa': '쿤디아와',
        'Chimoio': '치모이오',
        'Chimore': '치모레',
        'Trincomalee': '트링코말리',
        'Chinchilla': '친칠라',
        'Tete': '테테',
        'Chios Island': '키오스섬',
        'Chipata': '치파타',
        'Sault Ste Marie': '수세인트마리',
        'Eau Claire': '오클레어',
        'Chisana': '치사나',
        'Chisasibi': '치사시비',
        'Chisinau': '키시나우',
        'Chita': '치타',
        'Chitrakoot': '치트라쿠트',
        'Chitral': '치트랄',
        'Chitre': '치트레',
        'Chizhou': '츠저우',
        'Chlef': '슐레프',
        'Chofu': '초후',
        'Choibalsan': '초이발산',
        'Choiseul Bay': '초이즐베이',
        'Chokurdakh': '초쿠르다흐',
        'Choluteca': '촐루테카',
        'Chongjin': '청진',
        'Wushan': '우산',
        'Wulong': '우롱',
        'Chos Malal': '초스말랄',
        'Christmas Creek': '크리스마스크리크',
        'Chu Lai': '추라이',
        'Chuathbaluk': '추아트발룩',
        'Chub Cay': '처브케이',
        'Neryungri': '네룬그리',
        'Chumikan': '추미칸',
        'Chumphon': '춤폰',
        'Churchill': '처칠',
        'Churchill Falls': '처칠폴스',
        'Chuuk': '추크',
        'Santiago': '산티아고',
        'Cicia Island': '시시아섬',
        'Cijulang': '치줄랑',
        'Cincinnati': '신시내티',
        'Hebron': '헤브론',
        'Alaska': '알래스카',
        'Circle': '서클',
        'Londonderry': '런던데리',
        'Ciudad Constitucion': '시우다드콘스티투시온',
        'Loja': '로하',
        'Ciudad del Carmen': '시우다드델카르멘',
        'Ciudad Guayana': '시우다드과야나',
        'Ciudad Obregon': '시우다드오브레곤',
        'Ciudad Real': '시우다드레알',
        'Khajuraho': '카주라호',
        'Mangrove Cay': '맹그로브케이',
        'Grafton': '그래프턴',
        'Angeles': '안젤레스',
        'Clarks Point': '클라크스포인트',
        'The Valley': '더밸리',
        'Clayton': '클레이턴',
        'Clermont': '클레르몽',
        'Clermont-Ferrand': '클레르몽페랑',
        'Cleveland': '클리블랜드',
        'Clinton': '클린턴',
        'Little Rock': '리틀록',
        'Cloncurry': '클론커리',
        'Clovis': '클로비스',
        'Club Makokola': '클럽마코콜라',
        'Cluj-Napoca': '클루지나포카',
        'Clyde River': '클라이드리버',
        'Coari': '코아리',
        'Coatepeque': '코아테페케',
        'Cobar': '코바',
        'Cochin': '코친',
        'Coconut Island': '코코넛섬',
        'Cocos Islands': '코코스제도',
        'Coen': '코엔',
        'Coffee Point': '커피포인트',
        'Coffman Cove': '코프맨코브',
        'Coffs Harbour': '코프스하버',
        'Coimbatore': '코임바토르',
        'Cold Bay': '콜드베이',
        'Coldfoot': '콜드풋',
        'Coll': '콜',
        'Colonel Hill': '컬러넬힐',
        'Colonsay': '컬론세이',
        'Colorado Springs': '콜로라도스프링스',
        'Columbia': '컬럼비아',
        'Colville Lake': '콜빌레이크',
        'El Calafate': '엘칼라파테',
        'Bahia Blanca': '바이아블랑카',
        'Bage': '바게',
        'Comiso': '코미소',
        'Malarge': '말라르게',
        'Comox': '코목스',
        'Ponta Grossa': '폰타그로사',
        'Cruz': '크루스',
        'Con Dao Island': '콘다오섬',
        'Confresa': '콘프레사',
        'Spiddal': '스피달',
        'Pitalito': '피탈리토',
        'Contadora Island': '콘타도라섬',
        'Coober Pedy': '쿠버페디',
        'Cooch Behar': '쿠치베하르',
        'Cooktown': '쿡타운',
        'Cooma': '쿠마',
        'Coondewanna': '쿤데완나',
        'Copan Ruinas': '코판루이나스',
        'Coral Harbour': '코랄하버',
        'Corazon de Jesus': '코라손데헤수스',
        'Cordoba': '코르도바',
        'Corfu': '코르푸',
        'Cork': '코크',
        'Corn Islands': '콘아일랜즈',
        'Corner': '코너',
        'Governador Valadares': '고베르나도르발라다레스',
        'Ayacucho': '아야쿠초',
        'Tacna': '타크나',
        'Catamarca': '카타마르카',
        'Lencois': '렌소이스',
        'Corozal': '코로살',
        'Corpus Christi': '코퍼스크리스티',
        'Corrente': '코헨테',
        'Cortes+M4296': '코르테스M4296',
        'Cortez': '코르테스',
        'Corumba': '코룸바',
        'Corvo Island': '코르보섬',
        'Rivas': '리바스',
        'Coto 47': '코토47',
        'Latacunga': '라타쿤가',
        'Cottbus': '코트부스',
        'Coventry': '코벤트리',
        'Cox\'s Bazar': '콕스바자르',
        'Cozumel': '코수멜',
        'Craig Cove': '크레이그코브',
        'Craig': '크레이그',
        'Craiova': '크라이오바',
        'Cranfield': '크랜필드',
        'Creel': '크릴',
        'Croker Island': '크로커섬',
        'Crooked Creek': '크룩드크리크',
        'Cross Lake': '크로스레이크',
        'Crotone': '크로토네',
        'Cruzeiro do Sul': '크루제이루두술',
        'Cuamba': '쿠암바',
        'Cukurova': '추쿠로바',
        'Culpina': '쿨피나',
        'Cumbernauld': '컴버놀드',
        'Cunderdin': '컨더딘',
        'Cuneo': '쿠네오',
        'Cunnamulla': '커나멀라',
        'Willemstad': '빌렘스타트',
        'Cut Bank': '컷뱅크',
        'Meulaboh': '믈라보',
        'Cuyo': '쿠요',
        'St. Thomas Island': '세인트토머스섬',
        'Czestochowa': '체스토호바',
        'Da Nang': '다낭',
        'Singkep': '싱켑',
        'Dadu': '다두',
        'Dakhla': '다클라',
        'Borlange': '볼렝에',
        'Dalaman': '달라만',
        'Dalanzadgad': '달란자드가드',
        'Dalbandin': '달반딘',
        'Dali': '다리',
        'Damascus': '다마스쿠스',
        'Damaturu': '다마투루',
        'Damazin': '다마진',
        'Dambulla': '담불라',
        'Danbury': '댄베리',
        'Dandong': '단둥',
        'Dang Tarigaun': '당타리가운',
        'Dangriga': '당그리가',
        'Liberia': '라이베리아',
        'Tacloban': '타클로반',
        'Daocheng': '다오청',
        'Daporijo': '다포리조',
        'Daqing': '다칭',
        'Darab': '다라브',
        'Darbhanga': '다르방가',
        'Darnley Island': '단리섬',
        'Daru': '다루',
        'Sari': '사리',
        'DaSoguz': '다쇼구즈',
        'Datadawai': '다타다와이',
        'Datia': '다티아',
        'Datong': '다퉁',
        'Dauphin': '도핀',
        'Rote Island': '로테섬',
        'Tucson': '투손',
        'Dawadmi': '다와드미',
        'Dawei': '다웨이',
        'Dawson City': '도슨시티',
        'Glendive': '글렌다이브',
        'Dawson Creek': '도슨크리크',
        'Qeshm': '케슘',
        'Dayton': '데이턴',
        'Daytona Beach': '데이토나비치',
        'Dazhou': '다저우',
        'Den Helder': '덴헬더',
        'Prudhoe Bay': '프루도베이',
        'Deadman\'s Cay': '데드맨스케이',
        'Dease Lake': '디스레이크',
        'Deauville': '도빌',
        'Debrecen': '데브레첸',
        'Decatur': '디케이터',
        'Deer Lake': '디어레이크',
        'Deering': '디어링',
        'Mangshi': '망시',
        'Deir ez-Zor': '데이르에조르',
        'Leon': '레온',
        'Crescent City': '크레센트시티',
        'Del Rio': '델리오',
        'Deline': '델라인',
        'Delingha': '더링하',
        'Escanaba': '에스카나바',
        'Delta Junction': '델타정션',
        'Dembidolo': '뎀비돌로',
        'Deniliquin': '데닐리퀸',
        'Denizli': '데니즐리',
        'Deoghar': '데오가르',
        'Pangkalpinang': '팡칼피낭',
        'Kerinci': '크린치',
        'Deputatsky': '데푸타츠키',
        'Deqing': '더칭',
        'Dera Ghazi Khan': '데라가지칸',
        'Dera Ismail Khan': '데라이스마일칸',
        'Derby': '더비',
        'Des Moines': '디모인',
        'Copiapo': '코피아포',
        'Desolation Sound': '데솔레이션사운드',
        'OkaloosaC': '오칼루사C',
        'Destin-Fort Walton': '데스틴포트월턴',
        'Devils Lake': '데빌스레이크',
        'Devonport': '데번포트',
        'Karimun Java': '카리문자바',
        'Dezful': '데즈풀',
        'Dhaalu Atoll': '달루환초',
        'Dhangadhi': '당가디',
        'Dharavandhoo': '다라반두',
        'Diamantina': '디아만티나',
        'Dibrugarh': '디브루가르',
        'Dickinson': '디킨슨',
        'Dien Bien Phu': '디엔비엔푸',
        'Diffa': '디파',
        'Dijon': '디종',
        'Dikson': '딕손',
        'Dillingham': '딜링엄',
        'Dillon\'s Bay': '딜론스베이',
        'Dimapur': '디마푸르',
        'Dinard': '디나르',
        'Diomede': '디오메데',
        'Criciuma': '크리시우마',
        'Niamey': '니아메',
        'Dipayal Silgadhi': '디파얄실가디',
        'Dipolog': '디폴로그',
        'Shangri-La': '샹그릴라',
        'Diu': '디우',
        'Divinopolis': '디비노폴리스',
        'Diyarbakir': '디야르바키르',
        'kotte': '코테',
        'Djambala': '잠발라',
        'Djerba': '제르바',
        'Djibouti': '지부티',
        'Marietta': '마리에타',
        'Dobo': '도보',
        'Corrientes': '코리엔테스',
        'Dodge City': '도지시티',
        'Dodoma': '도도마',
        'Dole': '돌',
        'Dolisie': '돌리시',
        'Dolpa': '돌파',
        'San Juan': '산후안',
        'Sorong': '소롱',
        'Donakonda': '도나콘다',
        'Doncaster': '돈카스터',
        'County Donegal': '도네갈카운티',
        'DongHoi': '동호'
    }
    
    def get_korean_city_name(english_name):
        """영문 도시명을 한글 도시명으로 변환"""
        if pd.isna(english_name):
            return ''
        
        # 정확히 일치하는 경우
        if english_name in city_name_mapping:
            return city_name_mapping[english_name]
        
        # 대소문자 구분 없이 검색
        for eng_city, kor_city in city_name_mapping.items():
            if eng_city.lower() == english_name.lower():
                return kor_city
        
        # 부분 일치 검색 (공백 제거 후)
        english_clean = english_name.replace(' ', '').lower()
        for eng_city, kor_city in city_name_mapping.items():
            eng_clean = eng_city.replace(' ', '').lower()
            if english_clean == eng_clean:
                return kor_city
        
        # 매핑되지 않은 경우 빈 문자열 반환 (수동 확인 필요)
        return ''
    
    # 영문도시명 열 찾기
    city_column = None
    for col in df.columns:
        if '영문도시명' in col or 'city' in col.lower() or '도시' in col:
            city_column = col
            break
    
    if city_column is None:
        print("영문도시명 열을 찾을 수 없습니다. 열 이름을 확인해주세요.")
        print("현재 열 이름들:", df.columns.tolist())
        return None
    
    # 한글도시명 열 추가 (영문도시명 열 바로 오른쪽에)
    city_col_index = df.columns.get_loc(city_column)
    
    # 한글도시명 생성
    korean_cities = df[city_column].apply(get_korean_city_name)
    
    # 새로운 열을 원하는 위치에 삽입
    df.insert(city_col_index + 1, '한글도시명', korean_cities)
    
    # 매핑되지 않은 도시들 확인
    unmapped_cities = df[df['한글도시명'] == ''][city_column].unique()
    if len(unmapped_cities) > 0:
        print(f"\n매핑되지 않은 도시들 ({len(unmapped_cities)}개):")
        for city in unmapped_cities:
            if pd.notna(city):
                print(f"  - {city}")
        print("\n이 도시들은 수동으로 한글명을 추가해야 합니다.")
    
    # 파일 저장
    if output_file_path is None:
        base_name = csv_file_path.rsplit('.', 1)[0]
        output_file_path = f"{base_name}_with_korean_cities.csv"
    
    # CSV 파일로 저장 (UTF-8 BOM 인코딩으로 한글 깨짐 방지)
    df.to_csv(output_file_path, index=False, encoding='utf-8-sig')
    
    print(f"\n✅ 처리 완료!")
    print(f"📁 출력 파일: {output_file_path}")
    print(f"📊 총 {len(df)}개 행 처리됨")
    print(f"✅ 매핑된 도시: {len(df[df['한글도시명'] != ''])}개")
    print(f"❓ 매핑되지 않은 도시: {len(df[df['한글도시명'] == ''])}개")
    
    # 출력 파일 형태 예시 출력
    print(f"\n📋 출력 파일 구조:")
    print("영문공항명,한글공항,공항코드1(IATA),공항코드2(ICAO),지역,영문국가명,한글국가명,영문도시명,한글도시명,Latitude,longitude")
    print("A Coruna Airport,아코루냐 공항,LCG,LECO,유럽,Spain,스페인,ACoruna,아코루냐,43.3002595,-8.3796085")
    
    return df

# 사용 예시
if __name__ == "__main__":
    # CSV 파일 경로를 지정하세요
    input_file = "airport.csv"  # 실제 파일명으로 변경
    
    # 함수 실행
    result_df = add_korean_city_names(input_file)
    
    # 결과 미리보기
    if result_df is not None:
        print("\n결과 미리보기:")
        print(result_df[['영문도시명', '한글도시명']].head(10))