name: Functions Real Deploy

on:
  push:
    paths:
    - "functions/**"
    branches: [ deploy ]

jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: create dotenv
        run: |
          cd functions
          touch .env
          echo COUNTRYINFO_APIKEY=${{ secrets.COUNTRYINFO_APIKEY }} >> .env
          echo KOREABANK_APIKEY=${{ secrets.KOREABANK_APIKEY }} >> .env
          echo AMADEUS_KEY=${{ secrets.AMADEUS_KEY }} >> .env
          echo AMADEUS_SECRET=${{ secrets.AMADEUS_SECRET }} >> .env
          cat .env

      - uses: jsryudev/deploy-firebase-functions@v20.0.1
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_CI }}"
          FIREBASE_PROJECT: peekandfree