name: Real Deploy

on:
  push:
    paths:
    - "public/**"
    branches: [ deploy ]

jobs:
  build_and_website:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP }}"
          projectId: peekandfree
          channelId: live
